config/config.go
go.mod
go.sum
metrics/metrics.go
rpc/calls.go
rpc/client.go

add batch grpc message

---

rawkv/rawkv.go
rawkv/rawkv_test.go

followed original code.
https://github.com/pingcap/tidb/blob/7666f688b3d91ea84fa6b0a20c2e784fff3c8945/store/tikv/rawkv.go#L313-L358

add rawkv/ReverseScan

---

.travis.yml
Makefile

add travis CI

---

rpc/client.go

rpc: fix config bugs

---

proxy/httpproxy/handler.go
proxy/httpproxy/rawkv.go
proxy/rawkv.go

proxy: add support for reverse scan

---

metrics/push.go

Replace push.AddFromGatherer with push.New

Upgrade prometheus client to v1.x

---

txnkv/txn.go

the check of kv.IsErrNotFound(err) is unused in Transaction.Get

Delete some unused code

---

README.md

Signed-off-by: WangXiangUSTC <wx347249478@gmail.com>

fix grammary in readme

---

.travis.yml
go.mod
locate/codec.go
locate/region_cache.go
mockstore/mocktikv/mock.go
mockstore/mocktikv/pd.go
rawkv/rawkv.go
txnkv/oracle/oracles/pd.go
txnkv/store/errors.go
txnkv/store/store.go

related to https://github.com/tikv/client-go/issues/60
When someone needs to import tidb and go client at the same time, this PR should resolve to metrics conflict problem.

*: update pd client dependency

---

go.mod
mockstore/mocktikv/rpc.go
rawkv/rawkv.go
rawkv/rawkv_test.go
rpc/calls.go

Add a `ttl` additional field for put/batchput

Add ttl support

---

tikv/kv.go

Signed-off-by: AndreMouche
This PR adds a new function NewTxnClient, with this function, we can create a client for transactions with PD's address.

add NewTxnClient

---

locate/region_request_test.go
tikv/snapshot.go

- https://github.com/pingcap/tidb/pull/25236
- https://github.com/pingcap/tidb/pull/25416
- https://github.com/pingcap/tidb/pull/25429

*: sync updates from pingcap/tidb

---

metrics/metrics.go
tikv/kv.go

Update the SafeTS metrics

---

.github/workflows/lint.yml
.golangci.yml
locate/region_cache.go
tikv/kv.go

CI: add linter

---

metrics/metrics.go
tikv/kv.go

Refine the SafeTS gap metric

---

CONTRIBUTING.md
README.md

add contributing

---

.github/workflows/integration.yml
.github/workflows/lint.yml
.github/workflows/test.yml
integration_tests/tikv.toml

Also update some workflow file format.

support test with tikv

---

config/config.go
config/config_test.go

Make `GetTxnScopeFromConfig` return `TxnScope` from config directly

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
integration_tests/prewrite_test.go
util/misc_test.go
util/rate_limit_test.go

ref https://github.com/tikv/client-go/issues/97

util: replace pingcap/check with testify

---

retry/backoff_test.go

Signed-off-by: tison <wander4096@gmail.com>
close #139 
cc @disksing

retry: replace pingcap/check with testify

---

oracle/oracles/local_test.go
oracle/oracles/pd_test.go

Signed-off-by: tison <wander4096@gmail.com>
closes #118 
cc @disksing

oracle: replace pingcap/check with testify

---

integration_tests/1pc_test.go
integration_tests/async_commit_fail_test.go
integration_tests/async_commit_test.go

Fix https://github.com/tikv/client-go/issues/123
Fix https://github.com/tikv/client-go/issues/121

1pc_tesst, async_commit_test: replace pingcap/check with testify

---

client/client_test.go

client: fix test race

---

integration_tests/async_commit_test.go
integration_tests/go.mod
integration_tests/isolation_test.go
integration_tests/lock_test.go
integration_tests/safepoint_test.go
integration_tests/scan_mock_test.go
integration_tests/scan_test.go
integration_tests/snapshot_test.go
integration_tests/store_test.go
integration_tests/ticlient_test.go
integration_tests/util_test.go
tikvrpc/tikvrpc_test.go

*: remove dangling gocheck usages

---

client/main_test.go
integration_tests/main_test.go
tikv/failpoint_export.go
util/failpoint.go

Fix https://github.com/tikv/client-go/issues/145
cc @tiancaiamao @tisonkun

util: add flag to control all failpoints

---

client/client.go
integration_tests/go.mod
integration_tests/go.sum
mockstore/mocktikv/rpc.go
tikv/client.go

relates to https://github.com/pingcap/tidb/pull/25777

update tidb and clean up unused code

---

integration_tests/2pc_test.go

check in loop to stablize TestContextCancel2

---

tikv/2pc.go

As the title says.
Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

tikv: fix typo

---

tikv/lock_resolver.go

Fix https://github.com/pingcap/tidb/issues/25778, TiDB uses the same backoffer concurrently.

lock_resolver: fix backoff panic

---

examples/rawkv/rawkv.go
rawkv/rawkv.go

Step 1 of https://github.com/tikv/client-go/issues/200

Add rawkvclient with context parameters

---

tikv/scan.go
tikv/snapshot.go
tikv/test_probe.go

Signed-off-by: Xu Qiaolun <jamesxql@gmail.com>

txn: make scan batchSize configurable

---

.github/workflows/integration.yml
.github/workflows/test.yml
README.md

ci: simplify ci output

---

.golangci.yml
tikv/batch_getter.go
tikv/gc.go

To make sure exported functions or types have comments.

ci: add golint

---

README.md

readme: update stabability description

---

examples/txnkv/delete_range/delete_range.go
examples/txnkv/delete_range/go.mod

This PR adds an example for `delete_range`.

examples/txnkv: add example for delete_range

---

examples/txnkv/delete_range/delete_range.go
integration_tests/delete_range_test.go
integration_tests/range_task_test.go
tikv/gc.go
tikv/kv.go
tikv/split_region.go
txnkv/rangetask/delete_range.go
txnkv/rangetask/range_task.go

This PR inits package `txnkv/rangetask`, and it also adds a new function `DeleteRange` for `KVStore`

txnkv/*: init txnkv/rangetask package

---

examples/txnkv/unsafedestoryrange/go.mod
examples/txnkv/unsafedestoryrange/unsafedestoryrange.go
metrics/metrics.go
tikv/gc.go

This PR init function `UnsafeDestoryRange` for tikv/gc.
TODO:

tikv/gc: init UnsafeDestoryRange

---

integration_tests/cas_test.go
rawkv/rawkv.go
tikvrpc/tikvrpc.go

add raw cas feature

---

tikv/client_helper.go
tikv/snapshot.go

make https://github.com/pingcap/tidb/pull/17373 works again

tikv: use resolve lock lite for snapshot.Get()

---

README.md

readme: add juiceFS link

---

tikv/kv.go

The related PR:https://github.com/tikv/client-go/pull/250

tikv/kv.go: define NewLock since both tidb and br are using them

---

error/error.go
integration_tests/async_commit_test.go
integration_tests/lock_test.go
tikv/2pc.go
tikv/commit.go
tikv/kv.go
tikv/pessimistic.go
tikv/prewrite.go
tikv/test_probe.go
tikv/txn.go
txnkv/txnlock/lock.go
txnkv/txnsnapshot/client_helper.go
txnkv/txnsnapshot/scan.go
txnkv/txnsnapshot/snapshot.go
txnkv/txnsnapshot/test_probe.go
txnkv/txnutil/priority.go

This PR init package `txnkv/txnsnapshot`.

txnkv/txnsnapshot: init package for txnsnapshot

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
internal/locate/region_request.go
internal/locate/region_request_test.go

See https://github.com/tikv/tikv/pull/10600. 
This flag is to avoid unnecessary checks in the first sending.
The same change has been merged to TiDB 5.1: https://github.com/pingcap/tidb/pull/26482

add flag in Context for retried requests

---

examples/txnkv/pessimistic_txn/pessimistic_txn.go
integration_tests/2pc_test.go
integration_tests/async_commit_test.go
integration_tests/isolation_test.go
integration_tests/lock_test.go
integration_tests/prewrite_test.go
integration_tests/safepoint_test.go
integration_tests/snapshot_test.go
integration_tests/split_test.go
integration_tests/util_test.go
tikv/backoff.go
tikv/kv.go
tikv/split_region.go
tikv/test_probe.go
txnkv/transaction/2pc.go
txnkv/transaction/batch_getter.go
txnkv/transaction/batch_getter_test.go
txnkv/transaction/binlog.go
txnkv/transaction/cleanup.go
txnkv/transaction/commit.go
txnkv/transaction/pessimistic.go
txnkv/transaction/prewrite.go
txnkv/transaction/test_probe.go
txnkv/transaction/txn.go
txnkv/transaction_export.go

This PR init package `txnkv/transaction`.
Fix conflicts in https://github.com/tikv/client-go/pull/257

txnkv/transaction: init package

---

config/config.go

config: remove unused utility

---

txnkv/transaction/2pc.go

fixes https://github.com/pingcap/tidb/issues/27495

txnkv: fix delete temp table issue request to kv-server

---

internal/client/client.go
internal/client/client_batch.go
metrics/metrics.go
metrics/shortcuts.go

Manually cherry pick https://github.com/tikv/client-go/pull/270 https://github.com/tikv/client-go/pull/278 https://github.com/tikv/client-go/pull/279 to tidb-5.2 branch  for https://github.com/pingcap/tidb/pull/27688

metrics,client-go: update client-go and add batch client receive response metrics

---

.github/workflows/integration.yml
integration_tests/raw/cas_test.go
integration_tests/raw/rawkv_test.go
integration_tests/raw/tikv.toml
integration_tests/raw/ttl_test.go
integration_tests/raw/util_test.go

close https://github.com/tikv/client-go/issues/294

separate rawkv and txnkv tests

---

config/config.go
txnkv/txnlock/lock_resolver.go

ref https://github.com/pingcap/tidb/pull/25835
support change resolve lock lite threshold value in configuration and change nothing else

config: support config resolve lock lite threshold

---

internal/client/client_batch.go

client: fix some typos

---

config/client.go
config/config.go
txnkv/txnlock/lock_resolver.go

ref https://github.com/pingcap/tidb/pull/27691#issuecomment-911226021
tiny fix to move resolve-lock-lite-threshold into [tikv-client]

config: move resolve-lock-lite-threshold to tikv-client segment

---

error/error.go
integration_tests/2pc_test.go
integration_tests/async_commit_fail_test.go

Fix https://github.com/tikv/client-go/issues/299

error: add function to check if error is undetermined

---

internal/client/client_batch.go

Signed-off-by: Shuaipeng Yu <jackysp@gmail.com>

internal/client: demoted annoying log

---

internal/locate/region_request.go

add warn log if there is no target peer

---

internal/client/client.go
metrics/metrics.go

add metrics label for sending request

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
integration_tests/raw/rawkv_test.go
internal/kvrpc/batch.go
rawkv/rawkv.go

my issue: https://github.com/pingcap/kvproto/issues/807
I add ttls param for BatchPut request so that it can set independent ttl for every key

batchput add ttl to every key

---

internal/locate/region_request.go

fix unknown region error metrics

---

tikv/kv.go

Fix the doc for GetSnapshot

---

internal/unionstore/memdb.go
internal/unionstore/memdb_arena.go
kv/keyflags.go

Signed-off-by: you06 <you1474600@gmail.com>
This PR adds a flag for marking whether KV pairs can be read by in-transaction statements.

add readable flag

---

internal/mockstore/mocktikv/mock.go
internal/mockstore/mocktikv/mvcc.go
internal/mockstore/mocktikv/mvcc_leveldb.go
internal/mockstore/mocktikv/rpc.go

Fix https://github.com/tikv/client-go/issues/333

internal/mockstore: remove use of errors.Trace

---

error/error.go

errors: use As to check error type

---

internal/client/client.go

fix metrics error

---

internal/locate/region_cache.go
util/misc.go

Part of the https://github.com/tikv/client-go/issues/374.

locate, util: print the Region key with a more readable format

---

internal/locate/region_request.go

A strong willing drives me to fix this thing.

Fix a typo in a comment

---

kv/kv.go
txnkv/transaction/pessimistic.go

Signed-off-by: mornyx <mornyx.z@gmail.com>

txnkv: add ResourceGroupTagger for PessimisticLockRequest

---

examples/txnkv/txnkv.go
tikv/kv.go
txnkv/client.go

move tikv.NewTxnClient to txnkv.NewClient

---

integration_tests/go.mod
integration_tests/go.sum
txnkv/transaction/2pc.go

ref: [#30410](https://github.com/pingcap/tidb/issues/30410)
ref: https://github.com/pingcap/tidb/pull/30447
Try to add enhancement check logic for unnecessary key-value pairs, report error if unexpected situations are encountered.

txn: change IsUnnecessaryKeyValue interface to report error for unexpected paths

---

txnkv/transaction/2pc.go

ref: [30410](https://github.com/pingcap/tidb/issues/30410)
Try to cherry-pick https://github.com/tikv/client-go/pull/390 to tidb-5.2 release branch.

txn: change IsUnnecessaryKeyValue interface to report error(390)

---

txnkv/transaction/2pc.go

Fix the pick https://github.com/tikv/client-go/pull/398.

txn: fix the line delete doing pick.

---

txnkv/transaction/2pc.go

ref: [30410](https://github.com/pingcap/tidb/issues/30410)
Try to cherry-pick https://github.com/tikv/client-go/pull/390 to release tidb-5.3 branch.

txn: change IsUnnecessaryKeyValue interface to report error(#390)

---

rawkv/rawkv.go

close https://github.com/tikv/client-go/issues/409

docs: make it explicit that DeleteRange deletes [start, end)

---

integration_tests/raw/rawkv_test.go
rawkv/rawkv.go

ref https://github.com/tikv/client-go/issues/408

rawkv: split BatchPut and BatchPutTTL

---

README.md

*: update readme

---

integration_tests/lock_test.go
kv/kv.go

Signed-off-by: Yilin Chen <sticnarf@gmail.com>
(cherry picked from commit a6db0c9a3e9c79684c21ff6b0b46c42f8dfc377a)

Fix incorrect LockNoWait value (#435)

---

.github/workflows/compatibility.yml
.github/workflows/integration.yml
.github/workflows/test.yml

ci: enable CI for v2 branch

---

integration_tests/snapshot_fail_test.go

integration: try not to skip snapshotFailTest when run with tikv

---

integration_tests/assertion_test.go
internal/mockstore/mocktikv/errors.go
internal/mockstore/mocktikv/mvcc_leveldb.go
internal/mockstore/mocktikv/rpc.go

Fix https://github.com/tikv/client-go/issues/442

mockstore: fix assertion

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
txnkv/snapshot_export.go
txnkv/txnsnapshot/snapshot.go

Ref document: https://github.com/pingcap/tidb/pull/32806
Try to support the read-consistency isolation level read with tso checking.

txn: support read-consistency read with tso checking

---

util/execdetails.go

close #450 
Make it the same as that in kvproto.

fix the comment of TimeDetail

---

integration_tests/2pc_test.go
integration_tests/async_commit_test.go
integration_tests/resource_tag_test.go
integration_tests/util_test.go
internal/client/client.go
internal/client/client_batch.go
internal/client/client_interceptor_test.go
internal/client/client_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_test.go
internal/mockstore/mocktikv/rpc.go

Close https://github.com/tikv/client-go/issues/455

reconnect when meets store-not-match errors

---

rawkv/rawkv.go

add comment for rawkv scans

---

.github/workflows/test.yml
internal/client/client.go
internal/client/client_test.go

client: fix the race between connArray.Close() and connArray.Get()

---

internal/client/client.go
internal/locate/region_cache.go

fix linter warning

---

internal/unionstore/memdb_arena.go

internal/unionstore: avoid panic and add log for tidb issue/34307

---

integration_tests/async_commit_test.go
txnkv/transaction/prewrite.go

fix the vulnerability of atomicity in async commit (#492)

---

txnkv/transaction/prewrite.go

Set retry flag for tidb-5.4

---

txnkv/transaction/prewrite.go

Set retry flag for tidb-5.3

---

integration_tests/2pc_test.go
internal/client/client.go
internal/locate/region_cache.go
internal/locate/region_request.go
internal/locate/region_request3_test.go

Signed-off-by: Yilin Chen <sticnarf@gmail.com>

[tidb-5.3] Avoid sending requests to unhealthy leader (#503)

---

integration_tests/2pc_test.go
internal/client/client.go
internal/locate/region_cache.go
internal/locate/region_request.go
internal/locate/region_request3_test.go

Signed-off-by: Yilin Chen <sticnarf@gmail.com>

[tidb-5.4] Avoid sending requests to unhealthy leader (#503)

---

examples/gcworker/gcworker.go
examples/txnkv/1pc_txn/1pc_txn.go
examples/txnkv/async_commit/async_commit.go
examples/txnkv/delete_range/delete_range.go
examples/txnkv/pessimistic_txn/pessimistic_txn.go
examples/txnkv/unsafedestoryrange/unsafedestoryrange.go

Signed-off-by: 583373805 <583373805@qq.com>

fix:move tikv.NewTxnClient to txnk.NewClient

---

txnkv/transaction/2pc.go
util/execdetails.go

Signed-off-by: zyguan <zhongyangguan@gmail.com>
close #537

txn: also record get-latest-ts time in commit details

---

integration_tests/raw/api_test.go
internal/client/api_version.go
internal/client/api_version_test.go

Signed-off-by: haojinming <jinming.hao@pingcap.com>
support checksum for rawkv apiv2.

add checksum for apiv2

---

txnkv/transaction/2pc.go

txnkv: fix a bug that commitTSUpperBoundCheck err not handled

---

internal/locate/region_request.go

check log level to errror while encoutering key not in region

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
internal/locate/region_request_test.go
tikvrpc/tikvrpc.go

Close #569.
Ref: https://github.com/tikv/tikv/issues/13303, https://github.com/pingcap/tidb/issues/37197.

*: support the kv_flashback_to_version cmd

---

error/error.go
go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
internal/locate/region_cache_test.go
internal/locate/region_request.go

Ref https://github.com/tikv/tikv/issues/13397.

*: introduce the non-retryable error FlashbackInProgress

---

internal/locate/region_cache.go

Refer to https://github.com/pingcap/tidb/issues/37888
cc @hawkingrei

Avoid data race at workTiFlashIdx

---

internal/client/client.go
internal/locate/region_cache.go

Signed-off-by: Jack Yu <jackysp@gmail.com>
cherry-pick #574 to tidb-6.1

*: disable PermitWithoutStream to avoid too many pings (#574)

---

internal/mockstore/mocktikv/pd.go

Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>
ref [#5293](https://github.com/tikv/pd/issues/5293)

mocktikv: impl LoadKeyspace and WatchKeyspaces for  pd client

---

internal/locate/region_cache.go
internal/locate/region_request.go
tikvrpc/endpoint.go

1. fix bug in `reloadTiFlashComputeStores`, should only reload store whose state is up.
2. change all tiflash_mpp to tiflash_compute

region_cache: fix bug when reload tiflash_compute store cache

---

internal/apicodec/codec_v2.go
internal/client/client.go

ignore encode for tiflash requests

---

error/error.go
go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
internal/locate/region_cache_test.go
internal/locate/region_request.go

Introduce the FlashbackNotPrepared error

---

internal/apicodec/codec_v2.go
internal/client/client.go
tikv/region.go

encode requests toward tiflash server

---

txnkv/transaction/txn.go

ref https://github.com/pingcap/tidb/issues/39380
fix data race in test 

fix data race in test

---

tikv/kv.go

add GetAPIVersion for KVStore

---

internal/apicodec/codec_v2.go
internal/apicodec/codec_v2_test.go

refine keyspace region mapping

---

tikv/kv.go

Revert "add GetAPIVersion for KVStore"

---

internal/locate/region_cache.go
internal/locate/region_request.go

Signed-off-by: guo-shaoge <shaoge1994@163.com>

region_cache: region_cache: refine GetTiFlashComputeRPCContextByConsistentHash

---

tikv/client.go
txnkv/client.go

Signed-off-by: ystaticy <y_static_y@sina.com>

add gRPCDialOptions

---

internal/locate/region_cache.go

Signed-off-by: Smityz <smityz@qq.com>
fix https://github.com/tikv/client-go/issues/659
The root cause is `reResolve()` there will return true, even if the store's state is tombstone.
https://github.com/tikv/client-go/blob/master/internal/locate/region_cache.go#L2442
The existing unit test assumes if pd client gets a tombstone store, it will return nil, but in the force scale-in scenario, it won't.
https://github.com/tikv/client-go/blob/master/internal/mockstore/mocktikv/pd.go#L202-L208

add tombstone check

---

txnkv/transaction/txn.go

Cherry-picks #655 to tidb-6.1 branch

fix data race in the LockKeys

---

integration_tests/store_test.go
internal/locate/region_request3_test.go

fix integration test

---

integration_tests/go.mod
integration_tests/go.sum

integration: update tidb to master

---

internal/locate/region_request.go
internal/resourcecontrol/resource_control.go
tikvrpc/tikvrpc.go

Consider the number of replicas when calculating RU

---

internal/resourcecontrol/resource_control.go

ref https://github.com/tikv/pd/issues/5945
Signed-off-by: nolouch <nolouch@gmail.com>

resource_control: change the log level

---

internal/locate/region_cache.go

Signed-off-by: guo-shaoge <shaoge1994@163.com>

Increase consistent hash virtual nodes to 200 for better balance

---

tikv/gc.go
tikv/kv.go
tikv/pool.go
txnkv/transaction/2pc.go

tikv: configurable pool

---

internal/apicodec/codec.go
internal/apicodec/codec_test.go

ref: https://github.com/pingcap/tidb/issues/41758

fix attach api ctx error for unknown requests like StoreSafeTS

---

integration_tests/2pc_test.go

A test case is added in the PR https://github.com/tikv/client-go/pull/749 , but not included in the corresponding PR to tidb-7.0 branch (https://github.com/tikv/client-go/pull/750). This PR adds that test to tidb-7.0 branch

Port the test added in #749 to branch tidb-7.0

---

integration_tests/2pc_test.go
txnkv/transaction/2pc.go
txnkv/transaction/txn.go

cherry-pick 603f10d1c6779809b4ff77fd484404310b728aa8 + 3512be1d169eccbf1e215730e20b607feac3c87e + 3433ef848d98242e5a2ce4efa011b43bc761fb80

txnkv: add new API for lock->put optimization

---

util/execdetails.go

execdetails: add RRU/WRU interface of RURuntimeStats

---

internal/locate/cse/cse.go

This pull request checks if the buckets are reported before putting them in the resolved map.

fix panic while collects buckets

---

metrics/metrics.go

add const label for metrics

---

internal/apicodec/codec_v2.go

[master] encode store batch tasks

---

integration_tests/pd_api_test.go
integration_tests/raw/api_test.go
integration_tests/ticlient_test.go
oracle/oracle.go
tikv/kv.go
tikv/test_util.go
util/pd.go
util/pd_test.go

cp https://github.com/tikv/client-go/pull/793

Cherry pick `get store min resolved ts by api(#793)` to the tidb-6.5 branch

---

oracle/oracle.go
oracle/oracles/local.go
oracle/oracles/mock.go
oracle/oracles/pd.go
tikv/kv.go

Add a new function `GetMinTimestamp` for Oracle interface.

Add get min ts implementation

---

util/pd.go

PDHTTPClient: when meet GetStoreMinResolvedTS error just write in debug log

---

internal/locate/cse/cse.go

polish comments for cse region client

---

txnkv/txnlock/lock_resolver.go

[tidb-6.1] lock_resolver: let resolve lock timeout properly

---

internal/locate/region_cache.go

use '%d' instead of '%q' for some int values in error message

---

internal/locate/region_cache.go

ref https://github.com/tikv/client-go/issues/860

format key in error message in method `scanRegions`

---

txnkv/txnlock/lock_resolver.go

[tidb-7.1] lock_resolver: let resolve lock timeout properly

---

internal/locate/region_request.go
metrics/metrics.go
metrics/shortcuts.go

cherry-pick https://github.com/tikv/client-go/pull/878

*: fix stale read ops metric (#878)

---

internal/locate/region_request.go
internal/locate/region_request3_test.go

cherry pick #885 & #887 to 6.5

handle `mismatch peer id` region error

---

internal/client/client_batch.go
internal/locate/region_cache.go
internal/locate/region_request.go
internal/retry/backoff.go

use context logger as much as possible (#908)

---

txnkv/txnlock/lock_resolver.go

lock_resolver: let getTxnStatusFromLock return error when backoff timeout

---

integration_tests/pd_api_test.go
tikv/kv.go
util/pd.go

1. api interface
Nowadays we have 2 api interfaces for obtaining min resolved ts
- /pd/api/v1/min-resolved-ts: obtain cluster's min resolved ts
- /pd/api/v1/min-resolved-ts/{store_id}: obtain each store's min resolved ts
For client-go's updateSafeTS, we call `approach II` for each store, which is not necessary to call API so many times 
We can use the `approach I` to get cluster's min resolved ts when `@@txn_scope` is `global`
2. avoid using kv request reason:
if TiDB failed to connect a TiKV store to fetch the latest resolved_ts, it will remain the out-of-dated value until the TiKV comes back, though PD will mark the store as unavailable and keep updating the minimal resolved_ts with other TiKV stores. We may need to keep these two behaviors the same or unify them.
judge `@@txn_scope` …

min-resolved-ts: check dc label 

---

internal/client/client_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
tikvrpc/tikvrpc.go
txnkv/txnsnapshot/scan.go
txnkv/txnsnapshot/snapshot.go

add retry info to request source (#953)

---

tikv/gc.go
tikv/test_probe.go

cherry-pick #945 to release-6.5
* gc: add GCResolver interface for resolve locks

gc: add resolve locks interface for tidb gc_worker (#945)

---

.github/workflows/integration.yml
.github/workflows/test.yml
internal/client/client_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
tikvrpc/tikvrpc.go
txnkv/txnsnapshot/scan.go
txnkv/txnsnapshot/snapshot.go

Cherry pick #959 to standalone branch.

add retry info to request source (#953) (#959)

---

internal/client/client_fail_test.go
internal/client/client_test.go
internal/client/main_test.go
internal/client/mock_server/mock_tikv_service.go
internal/locate/region_request.go
internal/locate/region_request_test.go

*: fix issue of configure kv timeout not work when disable batch client (#980)

---

internal/locate/region_request.go
internal/locate/region_request3_test.go

*: configurable kv_read_timeout should not affect write request

---

internal/locate/region_request.go
internal/locate/region_request3_test.go

*: configurable kv_read_timeout should not affect write request (#978)

---

internal/client/client.go
internal/client/client_batch.go
metrics/metrics.go

This reverts commit #973.
Since I need to do more tests and the fix is not stable in another workload.

Revert "*: fix batch-client wait too long and add some metrics (#973)"

---

internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_test.go

pick https://github.com/tikv/client-go/pull/949

do not try leader if it's unreachable

---

internal/locate/region_request.go
internal/retry/backoff.go
internal/retry/backoff_test.go
internal/retry/config.go

Pick the https://github.com/tikv/client-go/pull/1002 and https://github.com/tikv/client-go/pull/1004 to the standalone branch.

add retry limit for excluded backoff type to avoid infinite retry

---

internal/locate/region_request.go
internal/locate/region_request3_test.go
tikvrpc/tikvrpc.go
txnkv/txnsnapshot/scan.go
txnkv/txnsnapshot/snapshot.go

Cherry pick #953 and #960 to 7.1.

request_source: add retry info to request source(#953)

---

internal/apicodec/codec.go
internal/client/client_batch.go
internal/client/client_fail_test.go
internal/client/client_test.go
internal/client/mock_server/mock_tikv_service.go
internal/locate/region_cache.go
internal/locate/region_request_test.go
tikvrpc/tikvrpc.go
util/misc.go

Fix batch client batchSendLoop panic (#1021)

---

internal/locate/region_request.go

ref #https://github.com/pingcap/tidb/issues/47753
cherry-pick #1025

fix request source tag unset

---

internal/locate/region_request.go

ref #https://github.com/pingcap/tidb/issues/47753
cherry-pick #1025

fix request source tag unset (#1026)

---

.github/workflows/compatibility.yml
internal/client/client_interceptor.go
internal/client/client_interceptor_test.go
tikv/kv.go
tikv/kv_test.go
util/execdetails.go

ref https://github.com/tikv/client-go/pull/1032

collecting the RU information

---

internal/locate/region_request.go

bugfix: fix invalid nil pointer when trying to record Store.SlownessStat. (#1017)

---

internal/locate/region_cache_test.go
internal/locate/sorted_btree.go

close #1089
UT and manual test

region cache: fix intersected stale check

---

internal/locate/region_request.go

avoid too frequent logs

---

.github/workflows/test.yml
.golangci.yml
internal/locate/region_cache.go
internal/mockstore/mocktikv/cluster.go
internal/unionstore/memdb.go
txnkv/transaction/txn.go
util/misc.go

use slices.Sort to eliminate bounds check
BTW, I find linter is old so i updated it.

use slices.Sort to eliminate bounds check

---

config/client.go
internal/client/client.go

ref https://github.com/pingcap/tidb/issues/50627

support grpc's shard buffer pool

---

go.mod
go.sum
internal/client/client_interceptor.go
internal/client/client_interceptor_test.go
tikv/kv.go
tikv/kv_test.go
util/execdetails.go

* collecting the RU information by pasing point through context.Value (#1032)
* add ruWaitDuration to RUDetails and update pd-client
---------

[pick-to-7.5] resource_control: add ru details in ExecDetails (#1070)

---

internal/locate/region_request3_test.go

close https://github.com/tikv/client-go/issues/1157

fix data race in ut

---

internal/locate/region_request.go
internal/locate/replica_selector_test.go

refine onNotLeader logic when new leader is not available

---

internal/locate/region_request.go
internal/locate/replica_selector_test.go

Don't invalid region in accessFollower when set user-defined req time out and meet DeadLineExceededErr

---

internal/locate/region_cache.go

related to https://github.com/pingcap/tidb/pull/51333

Add a new function `LocateKeyRange`

---

internal/locate/region_request.go
internal/locate/replica_selector_test.go

fix some issue of tryIdleReplica strategy

---

internal/locate/region_cache.go

Regions returned by `LocateKeyRange` must be ordered.
Has tested in https://github.com/pingcap/tidb/pull/51465

fix bug introduced by https://github.com/tikv/client-go/pull/1200

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum

ref https://github.com/grpc/grpc-go/releases/tag/v1.62.1

*: upgrade grpc 1.62.1

---

examples/gcworker/go.mod
examples/rawkv/go.mod
examples/txnkv/1pc_txn/go.mod
examples/txnkv/async_commit/go.mod
examples/txnkv/delete_range/go.mod
examples/txnkv/go.mod
examples/txnkv/pessimistic_txn/go.mod
examples/txnkv/unsafedestoryrange/go.mod
integration_tests/pipelined_memdb_test.go
txnkv/transaction/2pc.go
txnkv/transaction/pipelined_flush.go
txnkv/transaction/test_probe.go
txnkv/transaction/txn.go

When the resolve task crosses regions, it resolve the region repeatly without stop.

p-dml: fix unstopped resolve

---

internal/locate/replica_selector.go
internal/locate/replica_selector_test.go

shouldn't try leader first when leader's store is slow in prefer-leader strategy in replicaSelectorV2

---

internal/client/client.go
internal/client/client_batch.go
internal/client/client_test.go
internal/locate/region_request.go
internal/locate/region_request_test.go

Cherry pick:
- #1121
- #1134 
- #1140 
To fix following issues:
- #1120 
- #1138
- #1141

Pick connection handling improvements from tidb-cse-7.5

---

txnkv/transaction/txn.go

ref https://github.com/pingcap/tidb/issues/50215

feat: add pipeliend field in TxnInfo

---

config/client.go
internal/client/client.go
internal/locate/region_cache.go

cherry-pick https://github.com/tikv/client-go/pull/1239 to 7.5

[Cherry-pick-to-7.5] Add grpc window size config and change the default value

---

config/client.go
internal/client/client.go
internal/locate/region_cache.go

cherry-pick https://github.com/tikv/client-go/pull/1239 to 7.1

[Cherry-pick-to-7.1] Add grpc window size config and change the default value 

---

internal/client/client.go

Cherry-pick https://github.com/tikv/client-go/pull/1232 to fix issue introduced by #1223.

fix issue read req timeout bug cause by pr#1223 (#1232)

---

internal/locate/region_request.go
internal/locate/region_request_test.go

*: fix panic log when call RegionRequestSender.String method

---

go.mod
go.sum

update pd client to latest master.

*: update pd client to latest master

---

internal/locate/replica_selector.go
internal/locate/replica_selector_test.go

fix issue replica selector v2 not compatible with v1 in mixed mode

---

txnkv/transaction/txn_file.go

- Pick primary batch by primary key. As a chunk will belongs to multiple regions, the batch having smallest would not contain primary key.
- Rename `batch_map` to `batchMap` to conform Golang style.

txn-file: Pick primary batch by primary key

---

internal/locate/region_cache.go
internal/locate/region_request.go
internal/locate/region_request_test.go
internal/locate/replica_selector.go
internal/locate/replica_selector_test.go

reverts PR  #988 to fix transaction is undetermined cause by region invalid error

---

internal/locate/region_cache.go

ref:
- https://github.com/tikv/client-go/pull/1262
- https://github.com/pingcap/tidb/issues/46602

region_cache: cherry-pick #1262 to tidb-7.1

---

txnkv/transaction/2pc.go

ref tikv/tikv#16291
If a flush request is known to fail, don't continue sending other parts.

feat: stop flush when first error is met, like prewrite

---

internal/locate/region_cache.go
internal/locate/region_cache_test.go
rawkv/rawkv_test.go

- cherry pick #1127 to fix #1111

cherry pick some bug fixes to tidb-7.5

---

integration_tests/main_test.go
integration_tests/snapshot_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_test.go
metrics/metrics.go
tikv/region.go
txnkv/txnsnapshot/client_helper.go
txnkv/txnsnapshot/snapshot.go
txnkv/txnsnapshot/test_probe.go

improve region request log for diagnose (#1300)

---

config/client.go
internal/client/client_batch.go
internal/client/client_test.go

fix issue of doesn't fast fail request when no available connections (#1339)

---

internal/locate/region_request.go
internal/locate/region_request_test.go

*: fix panic in get cause error (#1344)

---

integration_tests/main_test.go
integration_tests/snapshot_test.go
internal/client/client_batch.go
internal/locate/region_cache.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_test.go
internal/retry/backoff.go
metrics/metrics.go
tikv/region.go
txnkv/txnsnapshot/client_helper.go
txnkv/txnsnapshot/snapshot.go
txnkv/txnsnapshot/test_probe.go

cherry-pick 
- https://github.com/tikv/client-go/pull/1300
- https://github.com/tikv/client-go/pull/908
- https://github.com/tikv/client-go/pull/1344

improve region request log for diagnose (1300)

---

internal/locate/region_cache.go

ref:
- https://github.com/tikv/client-go/pull/1262
- https://github.com/pingcap/tidb/issues/46602

region_cache: cherry-pick #1262 to tidb-7.5

---

internal/locate/region_cache.go

ref:
- https://github.com/tikv/client-go/pull/1262
- https://github.com/pingcap/tidb/issues/46602

region_cache: cherry-pick #1262 to tidb-6.5

---

internal/locate/region_cache.go
internal/locate/region_cache_test.go
internal/mockstore/mocktikv/cluster.go

region cache: check if the pd returned regions covers the ranges (#1377)

---

txnkv/transaction/txn_file.go

Close #1385 
- Check cached region and retry when it is nil

txn-file: Handle when cached region is nil

---

txnkv/transaction/txn_file.go

- Remove deprecated availability interface

txn-file: Remove availability interface

---

internal/locate/region_cache.go
internal/locate/region_cache_test.go
internal/locate/store_cache.go

fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed (#1402)

---

internal/client/client.go
internal/client/client_test.go

close issue #1357
cherry-pick #1359

fix rpc client panic cause by concurrent close (#1359)

---

txnkv/transaction/txn_file.go

- Prewrite/commit in parallel to improve performance.

txn-file: Prewrite/commit in parallel

---

txnkv/transaction/txn_file.go

- Lower log level of "group to batches" to debug

txn-file: Lower log level of "group to batches" to debug

---

internal/locate/region_cache.go
internal/locate/region_cache_test.go
internal/locate/store_cache.go

fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed 

---

internal/locate/region_request.go
internal/retry/backoff_test.go
internal/retry/config.go

Cherry pick #1423 to tidb-6.5 branch.

region_request: remove backoff for stale read (#1423)

---

integration_tests/main_test.go
integration_tests/snapshot_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_test.go
metrics/metrics.go
tikv/region.go
txnkv/txnsnapshot/client_helper.go
txnkv/txnsnapshot/snapshot.go
txnkv/txnsnapshot/test_probe.go

cherry-pick:
- https://github.com/tikv/client-go/pull/1300
- https://github.com/tikv/client-go/pull/1408

improve region request log for diagnose #1300

---

internal/unionstore/memdb_arena.go
internal/unionstore/memdb_test.go

Cherry pick #1393 to tidb-8.1.
ref #1394

memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum

ref https://github.com/pingcap/tidb/issues/56635

dep: update github.com/dgryski/go-farm

---

kv/variables.go
txnkv/transaction/txn_file.go

- Change switch variable to `DisableTxnFile` to make feature enable as default.

txn-file: Change switch variable to `DisableTxnFile`

---

internal/unionstore/memdb.go
internal/unionstore/memdb_arena.go
internal/unionstore/memdb_iterator.go
internal/unionstore/memdb_test.go

membuffer: fix memory leak in red-black tree (#1483)

---

oracle/oracles/pd.go

Cherry picks https://github.com/tikv/client-go/pull/1502 to tidb-7.1 branch

Fix the problem that adaptive update interval doesn't recovers back and there's too much logs about setting the config (#1502)

---

.github/workflows/compatibility.yml
integration_tests/go.mod
integration_tests/go.sum

change ci reference to original tidb

change ci reference to original tidb

---

go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
internal/locate/region_cache_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
internal/locate/region_request_state_test.go
internal/locate/region_request_test.go
oracle/oracle.go
oracle/oracles/export_test.go
oracle/oracles/local.go
oracle/oracles/mock.go
oracle/oracles/pd.go
oracle/oracles/pd_test.go
rawkv/rawkv.go
tikv/kv.go
tikv/region.go
tikv/split_region.go
txnkv/transaction/commit.go
txnkv/transaction/pessimistic.go
txnkv/transaction/prewrite.go
txnkv/txnsnapshot/client_helper.go
txnkv/txnsnapshot/scan.go

Cherry pick #1513 and #1533 to `tidb-7.5`.

Try to validate read ts for all RPC requests (#1513)

---

util/execdetails.go

Export scheduler write details for write requests.
TiDB slow query example:
```diff
@@ -380,7 +384,8 @@ func TestRuntimeStatsWithCommit(t *testing.T) {
"block: {cache_hit_count: 1, read_count: 1, read_byte: 100 Bytes, read_time: 20ms}}}, " +
"write_detail: {store_batch_wait: 10µs, propose_send_wait: 20µs, persist_log: {total: 30µs, write_leader_wait: 40µs, " +
"sync_log: 45µs, write_memtable: 50µs}, commit_log: 60µs, apply_batch_wait: 70µs, apply: {total:80µs, mutex_lock: 90µs, " +
-               "write_leader_wait: 100µs, write_wal: 101µs, write_memtable: 102µs}}}, resolve_lock: 1s, region_num:5, write_keys:3" +
+               "write_leader_wait: 100µs, write_wal: 101µs, write_memtable: 102µs}, scheduler: {process: 104µs, latch_wait: 103µs, " +
+               "pessimistic_lock_wait: …
```

execdetails: export scheduler write details

---

metrics/metrics.go

Ref https://github.com/pingcap/tidb/pull/59845

remove useless metric tidb_tikvclient_cop_duration_seconds_bucket

---

error/error.go
go.mod
go.sum
integration_tests/go.mod
integration_tests/go.sum
integration_tests/scan_test.go
internal/apicodec/codec_v2.go
internal/locate/region_cache.go
internal/logutil/hex.go
internal/mockstore/mocktikv/errors.go
internal/unionstore/union_iter.go
kv/key.go
tikv/split_region.go
txnkv/rangetask/range_task.go
txnkv/transaction/2pc.go
txnkv/transaction/commit.go
txnkv/transaction/pessimistic.go
txnkv/transaction/prewrite.go
txnkv/transaction/txn.go
txnkv/txnlock/lock_resolver.go
txnkv/txnsnapshot/scan.go
txnkv/txnsnapshot/snapshot.go
util/misc.go
util/redact/redact.go

(tidb-8.5) support redact key in logs (#1612)

---

config/nextgen_off.go
config/nextgen_on.go
tikv/kv.go

ref: https://github.com/pingcap/tidb/issues/60697

tikv: disable health-feedback in next-gen

---

error/error.go
error/error_test.go
internal/apicodec/codec_v2.go
internal/apicodec/codec_v2_test.go
txnkv/transaction/commit.go
txnkv/transaction/pipelined_flush.go
txnkv/txnlock/lock_resolver.go

txn: provide more information in commit RPC / log mvcc debug info when commit failed for `TxnLockNotFound`

---

internal/locate/region_cache.go

related tidb pr: https://github.com/pingcap/tidb/pull/62085

region_cache: add ForceRefreshAllStores function

---

examples/gcworker/go.mod
examples/rawkv/go.mod
examples/txnkv/1pc_txn/go.mod
examples/txnkv/async_commit/go.mod
examples/txnkv/delete_range/go.mod
examples/txnkv/go.mod
examples/txnkv/pessimistic_txn/go.mod
examples/txnkv/unsafedestoryrange/go.mod
internal/locate/region_cache.go
internal/locate/region_cache_test.go

For some functions that bypass the region cache, we should leave the exist region valid.
| Initial State | Bypass Region Cache | Finish State (old region) | Finish State (new region) |
| - | - | - | - |
| valid | yes | valid | valid |
| valid | no | valid | valid |
| invalid | yes | valid | invalid |
| invalid | no | valid | invalid |

region cache: do not invalidate the valid region cache when new region cache is loaded

---

internal/client/client_interceptor.go

When topsql is enabled, tidb will init `KvExecCounter` for each stmt and inject a `RPCInterceptor` to collect some info. And since async-batch-get is enabled by default, it can lead to a lot of warnings. This PR simply adds support for RPC interceptor by trigger it upon receiving the response.

client: support interceptor in SendRequestAsync

---

integration_tests/snapshot_test.go
internal/locate/region_request.go
internal/locate/region_request3_test.go
txnkv/txnsnapshot/snapshot.go
util/execdetails.go

This is a cherry-pick of #1532

*: Optimize executor runtime stats performance (#1532)
