- config/config.go
- locate/region_cache.go
- rawkv/rawkv.go
- rawkv/rawkv_test.go
- rpc/client.go
- txnkv/kv/buffer_store.go
- txnkv/kv/buffer_store_test.go
- txnkv/kv/mem_buffer_test.go
- txnkv/kv/union_store.go
- txnkv/kv/union_store_test.go
- txnkv/latch/latch.go
- txnkv/latch/latch_test.go
- txnkv/latch/scheduler.go
- txnkv/oracle/oracles/pd.go
- txnkv/store/batch.go
- txnkv/store/delete_range.go
- txnkv/store/lock_resolver.go
- txnkv/store/safepoint.go
- txnkv/store/scan.go
- txnkv/store/snapshot.go
- txnkv/store/split_region.go
- txnkv/store/store.go
- txnkv/store/txn_committer.go
> Move config variables to config package

- examples/rawkv/rawkv.go
- examples/txnkv/txnkv.go
- proxy/httpproxy/handler.go
- proxy/httpproxy/rawkv.go
- proxy/httpproxy/txnkv.go
- proxy/rawkv.go
- proxy/txnkv.go
- proxy/utils.go
- rawkv/rawkv.go
- rawkv/rawkv_test.go
- txnkv/client.go
- txnkv/kv/buffer_store.go
- txnkv/kv/buffer_store_test.go
- txnkv/kv/kv.go
- txnkv/kv/mem_buffer_test.go
- txnkv/kv/memdb_buffer.go
- txnkv/kv/mock.go
- txnkv/kv/union_iter.go
- txnkv/kv/union_store.go
- txnkv/kv/union_store_test.go
- txnkv/oracle/oracles/pd.go
- txnkv/store/lock_resolver.go
- txnkv/store/scan.go
- txnkv/store/snapshot.go
- txnkv/store/split_region.go
- txnkv/store/store.go
- txnkv/txn.go
> Use context everywhere

- examples/bench/bench.go
- metrics/metrics.go
- metrics/push.go
- rawkv/rawkv.go
- resources/grafana.json
- txnkv/store/snapshot.go
- txnkv/txn.go
- Add grafana template
- Adjust metrics
- Add `bench` example
Fixes #22
> *: better metrics support

- txnkv/txn.go
The unionstore use zero length value to indicate `Del`, but txn committer does not use `OpDel` for it. It will cause deleted key-values be seen by `scan`.
Related issues: https://github.com/tikv/tikv/issues/5047 https://github.com/tikv/tikv/issues/5058
> txnkv: fix commit bug

- .gitignore
- rawkv/rawkv.go
Signed-off-by: Yushen Lin <ldnvnbl@gmail.com>
fix https://github.com/pingcap/tidb/issues/14363
> fix RowKVClient scan method can't rightly break loop

- config/raw.go
- go.mod
- mockstore/mocktikv/rpc.go
- rawkv/rawkv.go
- rawkv/rawkv_test.go
As mention in #44 and in tikv/tikv#7673. It would helpful to have some kind of options for RawKv.
However, in order to avoid the breaking change and maintain API stability. We cannot just add a options parameter in RawKv API functions. We can put options somewhere in client object
implement another version of RawKv API functions with Option parameters, like GetWithOptions.
I choose to leave the Option in Config in this PR, but feel free to let me know if you feel other choice is better.
> Add Keyonly option for rawKv Scan

- go.mod
- mockstore/mocktikv/pd.go
- txnkv/latch/latch.go
Close #64.
The PD client version currently using has a performance regression problem which is fixed by tikv/pd#3169.
> Update the PD client version to eliminate performance regression

- locate/region_cache.go
Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>
> check region not nil to avoid nil pointer dereference panic

- client/client.go
there is a bug that compresses cannot work with maxInt64 in go-grpc  https://github.com/grpc/grpc-go/issues/4552
to work around, we can use `MaxInt64-1`
manual test passed
ref https://github.com/pingcap/tidb/issues/25419
> client: change maxRecvMsgSize to MaxInt64-1

- integration_tests/go.mod
- integration_tests/go.sum
Use a forked branch of TiDB to make integration_tests pass. We will reset it to `pingcap/tidb` after https://github.com/pingcap/tidb/pull/25559 is merged.
> Fix broken integration_tests

- latch/latch_test.go
- latch/scheduler_test.go
Signed-off-by: tison <wander4096@gmail.com>
closes #114 
cc @disksing 
I'm a bit confused by `scheduler_test.go#TestWithConcurrency` since it has no assertion but just validate code executed. We may take a closer look at the tests.
> latch: replace pingcap/check with testify

- client/client_fail_test.go
- client/client_test.go
- integration_tests/1pc_test.go
- integration_tests/2pc_test.go
- integration_tests/async_commit_fail_test.go
- integration_tests/async_commit_test.go
- integration_tests/delete_range_test.go
- integration_tests/isolation_test.go
- integration_tests/lock_test.go
- integration_tests/range_task_test.go
- integration_tests/rawkv_test.go
- integration_tests/safepoint_test.go
- integration_tests/scan_mock_test.go
- integration_tests/scan_test.go
- integration_tests/snapshot_fail_test.go
- integration_tests/snapshot_test.go
- integration_tests/split_test.go
- integration_tests/store_test.go
- integration_tests/ticlient_test.go
- integration_tests/util_test.go
- locate/region_cache_test.go
- locate/region_request_test.go
- mockstore/test_suite.go
- tikv/rawkv_test.go
- tikv/tikv_test.go
- tikvrpc/tikvrpc_test.go
As we are migrating to `testify`, later test suites cannot run in parallel. This PR makes all tests run in serial to test if there are any problems.
Test result shows that it runs faster in serial. I have no idea why.
```
norace+parallel       norace+serial        race+parallel        race+serial
unit-test           35.974s               25.274s              9.268s               4.315s
integration-test    47.216s               37.393s              54.462s              46.847s
```
> all tests run in serial

- integration_tests/2pc_test.go
Profile shows that `testCommitterSuite` uses too much memory. It could be the reason that test is been killed in CI.
```
5181904 testDeleteRangeSuite
8709096 testSplitSuite
19538784 testRangeTaskSuite
56275888 TestSetMinCommitTSInAsyncCommit
56395856 testStoreSerialSuite
56414864 testSafePointSuite
59393704 testSnapshotFailSuite
60530104 testSnapshotSuite
67307808 testScanSuite
68852040 TestTiclient
112780688 testStoreSuite
112813464 testScanMockSuite
283599256 testAsyncCommitSuite
338677600 testOnePCSuite
373290744 testRawKVSuite
400179416 testAsyncCommitFailSuite
1056385608 testLockSuite
2142688984 testCommitterSuite
```
> integration_tests: reduce memory usage

- internal/unionstore/memdb_norace_test.go
The test runs too slow (>1 minute on my machine). This PR reduces the data size.
> unionstore: speed up unit test

- error/error.go
- integration_tests/async_commit_test.go
- tikv/lock_resolver.go
- tikv/prewrite.go
Refer to https://github.com/pingcap/tidb/issues/25964 for more information.
> lock_resolver: avoid pessimistic transactions using resolveLocksForWrite

- config/config.go
- tikv/txn.go
If a client-go user needs to use async commit or 1PC, they need to set the configs for each transaction, which is not user-friendly.
This PR adds global switches for the two features.
We haven't claimed the supported TiKV version of this client. Considering large amount of TiKV 4.0 users, the default values of these settings are remained `false`.
This PR should not affect TiDB. TiDB sets the `enableAsyncCommit` and `enable1PC` settings according to session variables for each transaction.
> add global async commit and 1pc config

- tikv/snapshot.go
- util/ts_set.go
TSSet object allocation ranks Top3 during the point get operation.
It's a burden for Go GC as we observed in https://github.com/pingcap/tidb/issues/25573
This PR make the object allocation lazy, because not every transaction would meet lock conflict.
After this change, this object allocation is totally eliminated.
And the benchmark result in tidb shows
```
cd session
go test -test.run XXX -bench BenchmarkPreparedPointGet  -test.benchmem -test.benchtime 30s  -test.memprofile mem.out
```
Before vs After:
```
BenchmarkPreparedPointGet-16    	 3750292	      9442 ns/op	    7830 B/op	     101 allocs/op
BenchmarkPreparedPointGet-16    	 3824121	      9293 ns/op	    7702 B/op	      97 allocs/op
```
> util: make reduce tsset object allocation

- internal/locate/region_request.go
I've been working on improving TiDB's Point-Get performance, and I found out there is space for improvement in client-go.
So I merely replaced that `fmt.Sprintf()` with `strings.Builder`. By doing so, time cost of the function should be reduced to a half.
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>
> [internal]: improve RegionRequestRuntimeStats

- integration_tests/snapshot_fail_test.go
- tikv/snapshot.go
This PR intends to fix the jepsen failure https://github.com/tikv/tikv/issues/10552#issuecomment-879531922.
If the `minCommitTS` of some transaction was advanced before, and the snapshot timestamp is reset, we must also reset the `resolvedLocks`. Otherwise, the reader can read a stale result if only the primary lock is committed. (See the test as an example)
> reset resolvedLocks when setting snapshot ts

- integration_tests/2pc_test.go
- integration_tests/async_commit_fail_test.go
- integration_tests/async_commit_test.go
- integration_tests/lock_test.go
- tikv/2pc.go
- tikv/client_helper.go
- tikv/gc.go
- tikv/interface.go
- tikv/kv.go
- tikv/pessimistic.go
- tikv/prewrite.go
- tikv/scan.go
- tikv/snapshot.go
- tikv/test_probe.go
- txnkv/txnkv.go
- txnkv/txnlock/lock_resolver.go
- txnkv/txnlock/test_probe.go
This PR inits package txn/txnlock, moves tikv/lock_resolver.go into package txnlock.
> txnkv/txnlock: init Lock in txnlock package

- tikv/kv.go
This PR defines Lock & LockResolver back in package `tikv` since both tidb and br are using it. We could remove them once br and tidb are ready.
> tikv/kv.go: define Lock & LockResolver before updating tidb/br

- integration_tests/go.mod
- integration_tests/go.sum
- integration_tests/snapshot_test.go
- integration_tests/store_test.go
- tikv/kv.go
- txnkv/lock_export.go
- txnkv/snapshot_export.go
- txnkv/util_export.go
This PR moves temporary export types to package `txnkv`
> tikv: move temporary export types to package txnkv

- integration_tests/lock_test.go
- txnkv/transaction/2pc.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/txn.go
See https://github.com/pingcap/tidb/issues/26801 for what this PR wants to solve.
This PR starts the `keepAlive` goroutine after locking the primary key. So even if locking other keys takes a long time, the TTL of the primary lock will not expire.
However, before all keys are locked successfully, the primary lock may be determined. So if some keys fail to be locked and , we need to stop the heartbeat goroutine.
> Start heartbeat immediately after locking the primary key

- internal/locate/pd_codec.go
- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
To prevent the client from reporting errors slowly in such cases https://github.com/tikv/tikv/issues/10542, I ban the backoff in the region cache.
> locate: don't backoff if fails to decode region key

- integration_tests/util_test.go
- internal/client/client.go
- internal/client/client_fail_test.go
- internal/client/client_test.go
- internal/locate/region_request_test.go
- rawkv/rawkv.go
- tikv/client.go
- tikv/kv.go
use optional security argument so we don't have to pass empty security config every time.
> client: cleanup RPCClient options

- internal/client/client.go
- internal/client/client_batch.go
Move the `recycleIdleConnArray()` operation to a separate goroutine.
In our internal OnCall issue 3520 and 3381, I observed sending request blocked here when recycling idle connection.
recycle idle connection need to obtain the `recycleMu` write lock
when some connections are sending batch request, the `recycleMu` read lock is hold.
If the send batch request blocks for some reason (like TiFlash down), recycle idle connection will also be blocked by that, and then it blocks `SendRequest()` function.
I also consider some other options, like remove the recycle idle connection logic ... we introduce it because when some TiKV server are gone, there will be resource leak here. 
Anyway, this change is small and should fix the problem, the risk of side effect is low.
Signed-off-by: tiancaiamao …
> internal/client: fix recycle idle connection block sending request

- txnkv/transaction/txn.go
Expected to fix https://github.com/pingcap/tidb/issues/27400
> txnkv: Fix a bug that OnDeadlock callback is called before setting `IsRetryable` field

- txnkv/transaction/txn.go
Cherry-pick #274 to 5.2 branch
> txnkv: Fix a bug that OnDeadlock callback is called before setting `IsRetryable` field (#274)

- internal/client/client.go
- internal/client/client_batch.go
After mock testing, I find https://github.com/tikv/client-go/pull/270 is not sufficient to solve the problem.
To my surprise, **RLock can block RLock in [some case](https://www.zenlife.tk/go-read-mutex-block.md)**
The final decision is to reduce the granularity of the lock.
Just lock the modification of the `map`...
There is a risk that an idle connection become active again.
Since `recycleMu` is removed to protect such case, in very rare cases, someone maybe using the connection and the connection is closed by the recycle operation.
I think the outcome is acceptable, comparing to the recycle operation blocks the `SendRequest()` function.
> internal/client: remove the lock for idle connection recycle

- internal/client/client_batch.go
- metrics/metrics.go
- metrics/shortcuts.go
Add metrics for batch client recv duration.
(In those picture, there is no workload, so the duration goes to seconds ... in the real scenario it is us ~ ms)
This metrics is useful for us to locate some problem.
If TiKV server is too busy, and when it's channel is full, it might drop some message.
If the raft leader change meet some problems, it may also takes a long time ...
In those cases, there will be no response for a long time (or never?)
From this metrics we can check those case ... for example, if the duration goes to several minutes, something might be wrong.
> metrics,internal/client: add metrics for batch client stream receiving duration

- integration_tests/2pc_test.go
- internal/client/client.go
- internal/retry/backoff.go
- internal/retry/config.go
- rawkv/rawkv.go
- tikv/client.go
- txnkv/transaction/2pc.go
- txnkv/transaction/cleanup.go
- txnkv/transaction/commit.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/prewrite.go
- txnkv/txnlock/lock_resolver.go
After TiKV replaces write stall with scheduler flow control, region errors hardly happen if the cluster works normally.
https://github.com/tikv/tikv/pull/10771 tries to guarantee that the client can receive the response before the RPC timeout. If a write request queues for too long, the client will receive a TiKV busy error.
After these changes, I think it possible to not count backoff times due to TiKV busy. If TiKV returns busy, it probably means the error is recoverable, so we can always retry. And other region errors are unlikely to exist for a long time, if we keep receiving the errors, it is likely that these errors are not recoverable, so we would better to return them to the user.
> *: reduce max backoff time but don't count sleeps from busy errors

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- tikvrpc/tikvrpc.go
Added a `accessFollower` state that sends requests to followers or all replicas with mixed store option. The client uses `replicaReadSeed` to switch to different replicas for replica reads before. Now since the `replicaSelector` hold the context for requests, I remove the seed strategy and will remove more codes after this PR is merged.
> select replica for replica read requests using ReplicaSelector

- .github/workflows/compatibility.yml
As `br` is merged with tidb, there is no need to test its compatibility.
> ci: remove br compatibility test

- internal/locate/region_request3_test.go
- tikvrpc/tikvrpc.go
- txnkv/txnsnapshot/snapshot.go
txnScope indicates tso scope and request scope, as the txnSope in request only indicates request scope. I think it's more proper to rename it as request scope in order to avoid confused meaning.
> rename txnScope as readReplicaScope

- .gitignore
- error/error.go
- internal/locate/region_request.go
- internal/retry/config.go
- internal/unionstore/memdb.go
- metrics/shortcuts.go
Signed-off-by: tier-cap <zhengxiaojin@pingcap.com>
1. When TiKV is disk full, the original design is just return the disk full error to user without any retry.
2. Currently, need change to retry before return to user.
1. Use backoff to retry it when TiKV is disk full.
> *:rechange to retry when tikv disk full

- internal/locate/region_cache.go
In `OnSendFailForTiFlash`, it always record "switch peer" log, however, in most scenarios, TiFlash will batch all the regions in one TiFlash store into one request, so when meet send failure, this function is called repeatedly for all the regions, since one TiFlash store might contain thousands of regions, we need a way to avoid generating too much useless log.
> add `skipSwitchPeerLog` in `OnSendFailForTiFlash`

- integration_tests/async_commit_fail_test.go
CI for https://github.com/tikv/client-go/pull/315 [fails](https://github.com/tikv/client-go/pull/315/checks?check_run_id=3728456996) due to `TestSecondaryListInPrimaryLock`. The failure reason is that the region is not split in time.
This checks periodically whether the regions are split successfully to stablize the test.
> Fix flaky TestSecondaryListInPrimaryLock

- error/error.go
- integration_tests/client_fp_test.go
- internal/mockstore/mocktikv/rpc.go
- txnkv/transaction/2pc.go
Aims to remove parser dependency.
We will need to update tidb store/driver to convert client-go error to terror.ErrResultUndetermined.
> error: remove use of terror.ErrResultUndetermined

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- integration_tests/safepoint_test.go
pingcap/parser is merged to tidb. We should avoid using it.
> *: remove parser dependency

- .github/workflows/compatibility.yml
- integration_tests/go.mod
- integration_tests/go.sum
In order to merge https://github.com/pingcap/tidb/pull/29120, we introduce the https://github.com/tikv/client-go/pull/352 to do some temporary changes. This PR cleans up these temporary changes.
> Clean up the temporary changes

- internal/locate/region_cache.go
So that users and new developers of RegionCache can know what they should or should not do.
> Add thread safety explanation to RegoinCache's comment

- integration_tests/lock_test.go
- txnkv/transaction/prewrite.go
Ref: https://github.com/tikv/tikv/issues/11148
If an optimistic transaction encounters a lock with larger TS, this transaction will certainly fail due to a WriteConflict error. So we can construct and return an error early when prewrite encounters such a lock.
> Abort optimistic transaction when prewrite encounters a lock with larger TS

- integration_tests/lock_test.go
- txnkv/transaction/prewrite.go
Cherry picks #367 to tidb-5.2 to fix https://github.com/tikv/tikv/issues/11148
> Abort if the mismatching lock is from the current transaction when resolving locks (#367)

- .github/workflows/test.yml
- config/security.go
- config/security_test.go
- examples/gcworker/go.mod
- examples/rawkv/go.mod
- examples/txnkv/1pc_txn/go.mod
- examples/txnkv/async_commit/go.mod
- examples/txnkv/delete_range/go.mod
- examples/txnkv/go.mod
- examples/txnkv/pessimistic_txn/go.mod
- examples/txnkv/unsafedestoryrange/go.mod
- go.mod
Go 1.15 is EOL and 1.17 has been released for about 3 months (https://endoflife.date/go). It should be reasonable to bump required go version to 1.16. I'd like to revert the previous PR (#217).
> Bump go version to 1.16

- go.mod
- go.sum
- integration_tests/async_commit_test.go
- integration_tests/go.mod
- integration_tests/go.sum
- integration_tests/lock_test.go
- integration_tests/snapshot_fail_test.go
- internal/client/client_batch.go
- internal/locate/region_request.go
- tikv/kv.go
- tikv/test_probe.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/prewrite.go
- txnkv/txnlock/lock_resolver.go
- txnkv/txnlock/test_probe.go
- txnkv/txnsnapshot/client_helper.go
- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
TiKV supports read-through-lock https://github.com/tikv/tikv/pull/11238. This PR makes use of it:
1. I removed the `forWrite` parameter of `resolveLocks` because it's useless(https://github.com/tikv/client-go/pull/367) and add the `forRead`. If `forRead` is true, resolving secondary locks is asynchronous and `committedLocks` or `resolvedLocks` is returned to the user.
2. `ClientHelper` passes the `resolvedLocks` to `Context` to make use of read-through-lock.
Should be merged after https://github.com/pingcap/tidb/pull/29898
> txnkv: read through locks

- integration_tests/snapshot_test.go
- internal/retry/backoff_test.go
- internal/retry/config.go
- kv/variables.go
- txnkv/transaction/2pc.go
- txnkv/txnlock/lock_resolver.go
- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
1. Decrease some `MaxBackoff` to its old value.
2. Decrease the base backoff time of `BoTxnLockFast` from 100ms to 10ms, because 100ms is too big to endure for a small read request.
3. Decrease the base backoff time of `BoTxnLock` from 200ms to 100ms as the same reason for read. Because `BoTxnLock` is seldom used, I didn't decrease it a lot.
> txnkv: decrease some max and base backoff time

- tikv/kv.go
During tikv restarted, the safeTS might be 0 in a short period. This requests forbid tidb update backward safets.
> client: skip update backward safets

- txnkv/transaction/2pc.go
- txnkv/transaction/txn.go
This is used by the cached table https://github.com/pingcap/tidb/pull/30206
A brief description of the [cached table](https://github.com/pingcap/tidb/issues/25293):
We cache the table data directly in TiDB.
The cached table need to maintain a READ lock and renew the lock lease for caching.
For write operation, it first wait the READ lock lease to expire, then it changes to WRITE lock mode, and maintain the write lock lease for writing (prevent caching).
When transaction commit, we must guarantee **the final commitTS is less than the write lock lease** of a cached table,
otherwise the transaction should abort.
This PR add the transaction option.
> txnkv/transaction: add a kv option for cached table lock lease

- internal/client/client_batch.go
- metrics/metrics.go
Because of the mechanism of getting more requests, it is possible for the batch client to get more requests than the max-batch-size, so the original metrics observe position is not very accurate and the upper limit of metrics is too low, only 128.
> metrics: make batch client requests more accurate

- error/error.go
- internal/unionstore/memdb_norace_test.go
- tikv/kv.go
- txnkv/transaction/2pc.go
When you exit the KVStore, Some task will still call ```WaitGroup.Add```. It is a dangerous way to make DATA RACE and panic between ```WaitGroup.Wait``` and ```WaitGroup.Add```. 
https://github.com/pingcap/tidb/issues/30658
https://github.com/pingcap/tidb/issues/30651
> fix data race and panic when exiting

- metrics/metrics.go
`TiKVUnsafeDestroyRangeFailuresCounterVec` seems forget to register
> Add miss register for TiKVUnsafeDestroyRangeFailuresCounterVec

- integration_tests/2pc_test.go
TestCommitOnTiKVDiskFullOpt usually makes integration tests run too long. Use a timeout context to speed it up.
Signed-off-by: Yilin Chen <sticnarf@gmail.com>
> integration_tests: speed up TestCommitOnTiKVDiskFullOpt

- internal/retry/backoff.go
- internal/retry/backoff_test.go
- internal/retry/config.go
Closes https://github.com/tikv/client-go/issues/415
Before this PR, when `maxSleep` of a backoff is exceeded, the first error causing the backoff is returned. However, the first error may be just an accidental and temporary error.
For example, the first error can be a `txnLockFast` that is resolved very soon but later backoffs are all `regionMiss`. In this case, we expect the error returned should be "Region is unavailable", but the actual returned error is "resolve lock timeout", which is the error corresponding to `txnLockFast`.
We will encounter the similar problem if we use the last backoff type. The last error may be a temporary error, but most errors that causing the timeout can be something else. Then, the user may receive an unrepresentative error.
So this PR changes to return the …
> internal/retry: return the longest-sleeping type on backoff timeout

- integration_tests/delete_range_test.go
- internal/mockstore/mocktikv/mvcc_leveldb.go
- txnkv/rangetask/delete_range.go
See https://github.com/tikv/client-go/issues/428
Note: it only fix the issue on client side. We need to update tikv to resolve it completely.
> txnkv: fix the issue that deleteRange cannot use nil as endkey

- integration_tests/2pc_test.go
- integration_tests/delete_range_test.go
- integration_tests/isolation_test.go
- integration_tests/range_task_test.go
- integration_tests/raw/rawkv_test.go
- integration_tests/raw/util_test.go
- integration_tests/split_test.go
- integration_tests/ticlient_test.go
some cleanup. Make it easier for us to remove tidb dependency later.
> integration: use less tidb code

- integration_tests/assertion_test.go
- integration_tests/lock_test.go
- integration_tests/prewrite_test.go
- integration_tests/snapshot_fail_test.go
- integration_tests/util_test.go
add `NewTestUniStore` to create unistore for test. Original `NewTestStore` turns to use mockstore afterwards.
Some features are not supported by mockstore so we use unistore for now.
> integration: replace some unistore with mockstore

- integration_tests/lock_test.go
- kv/kv.go
Closes #434 
Fix the incorrect `LockNoWait` value following https://github.com/pingcap/kvproto/blob/9bb22e5a97fc47b9d27f4e053b44507217735f4d/proto/kvrpcpb.proto#L144
> Fix incorrect LockNoWait value

- internal/locate/region_request.go
- internal/retry/backoff.go
- internal/retry/backoff_test.go
Close: https://github.com/pingcap/tidb/issues/33265
Related changes:
- Avoid possible race changing the global backoff type config.
- Check nil before using the `longestSleepCfg` result.
- Copy the `configs`, `backoffSleepMS` and `backoffTimes` fields more deeply but not complete deeply.
The `Backoffer` is not very robust by now and it's easy to make mistakes, maybe we need to open a enhancement task for it in the future to avoid data races and related risks.
> backoff: deep copy the needed fields for backoffer type

- config/client.go
- txnkv/transaction/2pc.go
- txnkv/transaction/test_probe.go
Signed-off-by: Jack Yu <jackysp@gmail.com>
A simple test can provide some benefits such as, for sysbench insert workload, 1pc rate increases.
txnCommitBatchSize = 16k
txnCommitBatchSize = 1M
> config,txnkv: make txnCommitBatchSize adjustable by config

- config/client.go
- kv/store_vars.go
- txnkv/transaction/2pc.go
- txnkv/transaction/test_probe.go
Signed-off-by: Jack Yu <jackysp@gmail.com>
As title says. Asked by @morgo.
> *: use global variable instead of config for `TxnCommitBatchSize`

- .github/workflows/compatibility.yml
- .github/workflows/test.yml
golangci-lint failure relates to https://github.com/golangci/golangci-lint-action/issues/442
> fix compatibility test

- internal/client/client.go
- internal/client/client_test.go
- internal/locate/region_cache.go
Make `v` immutable after initialization.
> client: fix the race between connArray.Close() and connArray.Get()

- txnkv/transaction/prewrite.go
The existing failpoint can't handle concurrent `sleep` well. It might be a defect of the failpoint library.
So we need a separate failpoint to handle sleep to reproduce a bug pingcap/tidb#33641.
cc @MyonKeminta
> Add a failpoint to sleep before prewrite secondary

- internal/mockstore/mocktikv/pd.go
- tikv/split_region.go
Signed-off-by: qidi1 <1083369179@qq.com>
Issue Number: tikv/pd/issues/4095
Proposal PR:  pingcap/tidb/pull/33664
The original region split and scatter are handled by tikv and pd respectively, in order to improve efficiency, the split is also changed to be handled and controlled by PD.
In SplitRegions function,Using split api provide by PD instead of TiKV
Code changes based on this [work](https://github.com/hzh0425/pd/tree/add_split_and_scatter_region)
Thanks to [hzh0435](https://github.com/hzh0425)
Tests
Code changes
Side effects
> tikv:move split region request to pd

- tikv/split_region.go
This doesn't usually happen, but if it uses the mock version of PD (for example, run tidb with unistore), it may get nil, so it's better to double-check.
> tikv: check nil response of split region

- internal/locate/region_request.go
Try to print the original error and more information before return the injected  `recv error`, so that we could know if the actual RPC is executed successfully.
> request: print original error if the recv failure is injected

- internal/mockstore/mocktikv/pd.go
- tikv/split_region.go
This patch will break tests in TiDB and currently there is no corresponding PR in TiDB side. We should revert it now, maybe consider do it when it is all ready.
> Revert "tikv:move split region request to pd (#459)"

- integration_tests/lock_test.go
- kv/kv.go
Cherry picks https://github.com/tikv/client-go/pull/435 to tidb-5.2 branch
> Fix incorrect LockNoWait value (#435)

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
When  key is in [region startkey, first bucket key) or [last bucket key, region endkey), it's better not to return nil, as they can be considered to be `Bucket`.
> region_cache: in some cases, LocateBucket should not return nil.

- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
```
==================
WARNING: DATA RACE
Write at 0x00c001ff5c98 by goroutine 80:
github.com/tikv/client-go/v2/txnkv/txnsnapshot.(*KVSnapshot).SetResourceGroupTagger()
/home/prow/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220406091203-f73ec0e675f4/txnkv/txnsnapshot/snapshot.go:756 +0x78a
github.com/pingcap/tidb/store/driver/txn.(*tikvSnapshot).SetOption()
/go/tidb/store/driver/txn/snapshot.go:119 +0x73c
github.com/pingcap/tidb/executor.setOptionForTopSQL()
/go/tidb/executor/executor.go:2016 +0x67
github.com/pingcap/tidb/executor.(*PointGetExecutor).Open()
/go/tidb/executor/point_get.go:197 +0x10eb
github.com/pingcap/tidb/executor.(*baseExecutor).Open()
/go/tidb/executor/executor.go:186 +0x2ad …
```
> *: fix data race on the SetResourceGroupTagger

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
Signed-off-by: SpadeA-Tang <u6748471@anu.edu.au>
> region_cache: rename LocateBucketV2 to LocateBucket and let the old LocateBucket be the internal function of the new LocateBucket

- integration_tests/async_commit_test.go
- txnkv/transaction/prewrite.go
To fix https://github.com/pingcap/tidb/issues/33641
- For a pessimistic async commit txn, set its TTL to be at least (max commit ts - start ts)
> fix the vulnerability of atomicity in async commit

- internal/locate/region_cache.go
Signed-off-by: SpadeA-Tang <u6748471@anu.edu.au>
> region_cache: Add comments for LocateBucket

- internal/locate/region_cache.go
- metrics/metrics.go
- metrics/shortcuts.go
Signed-off-by: you06 <you1474600@gmail.com>
This PR record the latency when loading the region cache.
> metrics: add loading region cache duration

- txnkv/txnlock/lock_resolver.go
`ResolveLocksDone` incorrectly clear all arrays in `resolving[callerStartTS]`. It will cause panic when `UpdateResolvingLocks` updates resolving.
> Fix incorrect clear of resolving array

- internal/client/client.go
Introduced by https://github.com/tikv/client-go/issues/464. Connections can be nil if fails to connect some stores.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a39f6b]
goroutine 47779631 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0)
/go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:1059 +0x4b
github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc326b88140)
/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220530055857-75d3f86f3ba8/internal/client/client.go:242 +0x56
github.com/tikv/client-go/v2/internal/client.(*connArray).Init(0xc326b88140, {0xc001cd8978, 0x12}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, …
```
> client: fix nil dereference when closing conns

- integration_tests/2pc_test.go
- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
It's an improvement for recovery time when hibernate region is enabled.
When we detect a TiKV store is unreachable, we only clear the region cache of regions on it. But it's not enough.
Considering one TiKV is unhealthy, all requests sending to that store will timeout. But due to hibernate region, the regions whose leaders are on the unhealthy store will not be re-elected until a request is sent to the follower.
If there are thousands of such regions, every time we are accessing a new region, it will send a request to the original leader on the unhealthy TiKV because the leader definitely does not change. And then, the user will always experience very long request duration until all regions are touched and elect new leaders.
So, this PR simply prevents sending requests to the leader that …
> Avoid sending requests to unhealthy leader

- txnkv/transaction/2pc.go
Signed-off-by: Jack Yu <jackysp@gmail.com>
The undetermined error after prewriteMutations should be from async commit/1PC.
> transaction: update undetermined error log

- go.mod
- go.sum
- integration_tests/go.sum
- integration_tests/snapshot_test.go
- internal/client/client.go
- metrics/metrics.go
- tikvrpc/tikvrpc.go
- txnkv/transaction/commit.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/prewrite.go
- util/execdetails.go
This PR collects newly added `WriteDetail` and other time details returned from TiKV when handling the most dominant write requests (prewrite, commit and pessimistic lock).
> Handle more detailed statistics from TiKV

- internal/retry/backoff_test.go
- internal/retry/config.go
Signed-off-by: nolouch <nolouch@gmail.com>
Once the `data not ready` error is encountered, it will back off and try the next peer. BTW, most scenarios using stale read are latency sensitive, 100ms is a relatively large value.
such as:
> retry: make backoff more reasonable for DataNotReady

- internal/client/client.go
- tikvrpc/tikvrpc.go
When a response does not include `ExecDetailsV2`, `GetExecDetailsV2` will return an error. It formats a string to generate the error. It is useless but may cost much resource. Let's just don't produce that error.
> Do not format error when response does not include ExecDetailsV2

- internal/retry/backoff_test.go
- internal/retry/config.go
Signed-off-by: nolouch <nolouch@gmail.com>
pick #550
> [tidb-6.1] retry: make backoff more reasonable for DataNotReady (#550)

- internal/client/client.go
- internal/client/client_test.go
- internal/mockstore/mocktikv/cluster.go
- util/execdetails.go
Signed-off-by: zyguan <zhongyangguan@gmail.com>
In order to show `ExecDetailsV2` in the [trace statement](https://docs.pingcap.com/tidb/dev/sql-statement-trace), we have to convert the struct to spans of opentracing. This PR add the ability to do it.
<details>
<summary>Here is an example.</summary>
```sql
/* a */ drop table if exists t;
-- a >> 0 rows affected
/* a */ create table t (a int, b int, primary key(a), key sk(b));
-- a >> 0 rows affected
/* a */ insert into t values (1, 10), (5, 50);
-- a >> 2 rows affected
/* a:query */ trace select * from t where b < 100;
-- a >> +------------------------------------------------------------+-----------------+------------+
-- a    |                         operation                          |     startTS     |  duration  |
-- a …
```
> support adding `ExecDetailsV2` to tracing

- .github/workflows/test.yml
- internal/client/client.go
`latHist` should be inserted into `rpcNetLatencyHistCache` while we inserted it into `sendReqHistCache` due to a code-paste mistake.
> Fix that histogram is not inserted into rpcNetLatencyHistCache

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/sorted_btree.go
> Clear intersecting regions in the cache when inserting a region

- rawkv/rawkv.go
TxnAPI exposes GetPDClient
To ensure consistency in the semantics of the API, the rawkv API should also expose it
> *: add getPDClient to rawKV public api

- integration_tests/go.mod
- integration_tests/go.sum
Change back the tidb dependency in the integration test as it's temporarily changed in https://github.com/tikv/client-go/pull/567.
> update dependency of integration test

- kv/keyflags.go
To fix a bug caused by the loss of PresumeKNE flag in statement retry in pessimistic transactions.
> add a flag PreviousPresumeKNE

- integration_tests/2pc_test.go
- txnkv/transaction/test_probe.go
- txnkv/transaction/txn.go
Signed-off-by: TonsnakeLin <lpbgytong@163.com>
At first, we enable  lock_only_if_exists mode only when the primary key of the current transaction is selected when lock keys.
We expand the use scope, if the number of  keys to be locked is one, we also enable lock_only_if_exists even though the primary key is not selected.
> extend the scope of using lock_only_if_exists 

- txnkv/transaction/2pc.go
- txnkv/transaction/prewrite.go
If a pessimistic transaction has its for_update_ts = 0, we set it to its start_ts so that it is prewritten in the pessimistic way in TiKV, making it seems more consistent.
> Don't let pessimistic txn prewrite in the optimistic way

- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
- txnkv/txnsnapshot/test_probe.go
Signed-off-by: crazycs520 <crazycs520@gmail.com>
This is used for https://github.com/pingcap/tidb/pull/37466
> txnkv: export DefaultScanBatchSize variable

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- internal/locate/region_request_test.go
- tikvrpc/tikvrpc.go
ref https://github.com/tikv/tikv/issues/13519
> *: Support `kv_prepare_flashback_to_version` cmd

- integration_tests/2pc_test.go
- txnkv/transaction/2pc.go
In https://github.com/tikv/client-go/pull/585, I forgot to unlock in all branches in extractKeyExistsErr. So, if it goes into !c.txn.us.HasPresumeKeyNotExists(err.GetKey()) branch, the lock is never released.
Actually, it's unlikely to reach that branch because Op_Insert is only generated when there is a PresumeKeyNotExists flag. The only exception I find is amending transaction. It directly generates Op_Insert entries.
> Fix the missing unlock in extractKeyExistsErr (tidb-6.1)

- integration_tests/assertion_test.go
- txnkv/transaction/2pc.go
To fix https://github.com/pingcap/tidb/issues/38365
Stash the assertion error found in client-go; report it after prewrite succeeds
> Fix the false positive assertion error caused by loss of pessimistic locks 

- tikv/kv.go
fix https://github.com/tikv/tikv/issues/13675
TiKV will return `0` for `CmdStoreSafeTS` RPC when there is no region leader on a store. We should ignore this store when caculate the minSafeTS.
> tikv: skip 0 when call `getMinSafeTSByStores`

- util/misc.go
- util/misc_test.go
The GC-related time stored in TiKV is inconsistent with the time stored in PD. The value in TiKV, the time format is "20060102-15:04:05 -0700", and the precision is only seconds. In PD, it stores a uint64 with millisecond precision.
The if we use the value got from TiKV to do some processes, it will got a error like this,
```
mysql> flashback cluster to timestamp '2022-11-07 10:34:00';
ERROR 9006 (HY000): GC life time is shorter than transaction duration, transaction starts at 2022-11-07 10:34:00 +0800 CST, GC safe point is 2022-11-07 10:34:00.366 +0800 CST
```
> util: update GCTimeFormat to be the same as the value stored in PD

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- txnkv/transaction/2pc.go
- txnkv/transaction/commit.go
- txnkv/transaction/prewrite.go
- txnkv/transaction/txn.go
we use `u64` to reserve more space for future use. For now, the upper application is limited to setting this value under `0x80`, so there will no more cost to change it to `u64`
Signed-off-by: xiongjiwei <xiongjiwei1996@outlook.com>
> txn: make `txn_source` be u64 type

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
https://github.com/pingcap/kvproto/pull/1016/
add `start_ts` and `commit_ts` in prepare phase
> go.mod: update kvproto to adapt flashback

- internal/locate/region_cache.go
- tikv/kv.go
compute the min safe ts on the query path is expensive because it has to allocate thousands of small objects with lock, when there are hundreds of tikv node. this makes stale read using session variable `tidb_read_staleness` noticeable slower than normal read.
the safe ts from tikv are only updated every 2 seconds, thus the min safe ts could be precomputed on the update path to avoid the expensive computation on query path.
result on our benchmark 
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-74d134e2-7fff-1006-4985-b6a1f5d8d040"><div dir="ltr" style="margin-left:0pt;" align="left">
  | p99 | p999 | Cpu usage
-- | -- | -- | --
Leader read + tidb_low_resolution_tso | 4.0ms | 14.1ms | 413%
Stale read | 10.1ms | 40.3ms | 486%
Stale read with precomputed min …
> precompute min safe ts

- internal/unionstore/memdb_arena.go
ref: pingcap/tidb#39611
We shall not call a.onMemChange() in `alloc`, since it will make the latest block empty if the callback finally decides to panic, which breaks a precondition  for some operations (e.g. revertToCheckpoint)
> fix: do not call onMemChange in alloc

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- txnkv/transaction/2pc.go
close #630
Benchmark program 
```
package main
import (
"context"
"database/sql"
"flag"
"fmt"
"log"
"time"
"sync/atomic"
"github.com/jamiealquiza/tachymeter"
_ "github.com/go-sql-driver/mysql"
)
var (
host     = flag.String("h", "127.0.0.1", "host")
port     = flag.Int("P", 4000, "port")
user     = flag.String("u", "root", "username")
password = flag.String("p", "", "password")
)
func openDB() (*sql.DB, error) {
dbDSN := fmt.Sprintf("%s:%s@tcp(%s:%d)/test", *user, *password, *host, *port)
db, err := sql.Open("mysql", dbDSN)
if err != nil {
return nil, err
}
return db, nil
}
func mustExec(db *sql.DB, query string, args ...interface{}) {
_, err := db.Exec(query, args...)
if err != nil {
log.Fatal(err)
}
}
func assert(err error) {
if err != nil {
log.Fatal(err)
}
}	
func main() { …
```
> use goroutine pool to avoid the `runtime.newstack` call

- internal/locate/region_cache.go
- internal/locate/region_request.go
Signed-off-by: guo-shaoge <shaoge1994@163.com>
Move `GetTiFlashComputeStores()` outside of `GetTiFlashComputeRPCContextByConsistentHash()` to help filter alive tiflash_compute nodes.
Related tidb pr: https://github.com/pingcap/tidb/pull/40008
> region_cache: refine GetTiFlashComputeRPCContextByConsistentHash

- internal/locate/region_cache.go
- internal/mockstore/mocktikv/cluster.go
- tikv/kv.go
- tikv/kv_test.go
- tikv/test_probe.go
Signed-off-by: hehechen <awd123456sss@gmail.com>
MinSafeTS support TiFlash to support TiFlash stale read.
> MinSafeTS support TiFlash

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- tikv/kv.go
- txnkv/transaction/2pc.go
> bind the goroutine pool with store and close on Close

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
This can't guarantee the task is consumed by the new spawned goroutine
```
go worker(p)
p.ch <- f
```
so change it to
```
go worker(p, f)
```
https://github.com/tiancaiamao/gp/commit/917088386b9f950d611e2dcb14a1efcb696702f9
> go.mod: update github.com/tiancaiamao/gp

- integration_tests/2pc_test.go
- internal/mockstore/mocktikv/errors.go
- internal/mockstore/mocktikv/mvcc_leveldb.go
- txnkv/transaction/txn.go
This PR fixes a bug that when inserting on a key that's locked during the previous aggressive locking stage, it may not check the key's existence correctly. Also added more test cases to cover more cornercases of aggressive locking.
Ref: https://github.com/tikv/tikv/issues/13298
> Fix incorrect insertion behavior in aggressive locking mode and add tests

- integration_tests/2pc_test.go
- txnkv/transaction/txn.go
ref https://github.com/pingcap/tidb/pull/40350
> fix data race in the LockKeys

- internal/locate/region_request.go
Signed-off-by: Lucasliang <nkcs_lykx@hotmail.com>
When I was doing relevant optimization on ReadMode, I found there existed a bug on Round-Robin strategy when `ReadMode == ReplicaReadMixed`.
Supposing that we have a TiKV cluster with 3 nodes - [node 1, node 2, node 3].
Firstly, the cluster keeps in normal state, the Read flows sent to each nodes are in Uniform Distribution.
And if we made one node abnormal, taking Node 1 as the choice, all flows sent to Node 1 would be redirected to Node 3.
```Go
//       [Node 1]                                         [Node 1]
//      /        \                                       /        \
//     /          \          [Node 2] abrnomal ===>     /          \  
//    /            \                                   /            \
// [Node 2] --- [Node …
```
> Bug fix: fix the Round-Robin algorithm when "ReadMode == ReplicaReadMixed".

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- kv/store_vars.go
Signed-off-by: Yang Zhang <yang.zhang@pingcap.com>
> Support learner replica read

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request3_test.go
Refers to https://github.com/pingcap/tidb/issues/40461.
https://github.com/tikv/client-go/pull/566 can solve high CPU cost problems like https://github.com/tikv/client-go/issues/532. But in some cases, there will still be memory leaks when some of the stale regions are never touched again.
This PR adds a background goroutine to iterate over the cache to clean up stale region info. We don't want this goroutine to affect performance, so it runs at low frequency and each round is very fast.
> Add a background region cache GC goroutine

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
https://github.com/tikv/client-go/pull/664 was incomplete. The searching cursor increases monotonically without rewinding. So, if the regions split after the cursor passes their start keys, they will not be cleared after being stale.
This PR rewinds the cursor after reaching the end.
> Rewind after region cache GC reaches the end

- internal/locate/region_cache.go
The default virtual nodes is 20. Increase to 200 so that requests will be distributed more evenly.
Nginx uses [160 by default](https://www.nginx.com/resources/wiki/modules/consistent_hash/).
> Increase consistent hash virtual nodes to 200 for better balance

- rawkv/rawkv.go
Signed-off-by: Ping Yu <yuping@pingcap.com>
Close #696 
- invoke `cancel()` to release `ctx` in `bo` when there is no error.
Run this same program for reproducing in #696, the memory usage is stable and low for hour.
> rawkv: Fix context leak in rawkv.BatchPut

- rawkv/rawkv.go
Close #696 (https://github.com/tikv/client-go/issues/696#issuecomment-1430868197)
- invoke `cancel()` to release ctx in `bo` when there is no error.
Run this same program for reproducing in https://github.com/tikv/client-go/issues/696#issuecomment-1430868197, the memory usage is stable and low for tens of minutes.
> rawkv: Fix context leak in BatchDelete

- txnkv/transaction/txn.go
Locking commands skipped by `lock_only_if_exists` were mistakenly calculated as successfully locked for aggressive locking.
> fix: lock_if_exist + aggressive locking

- txnkv/transaction/2pc.go
We need to also support track PessimisticLock request by resource group. The correspending changes at tidb side is https://github.com/glorv/tidb/commit/99b36924e7a8d4b836052de1648be02e0b374054.
> txn: set group name in twoPhaseCommitter

- metrics/metrics.go
- metrics/shortcuts.go
- txnkv/transaction/txn.go
- txnkv/txnsnapshot/snapshot.go
- util/request_source.go
ref: https://github.com/pingcap/tidb/issues/41203
Add source scope for the `TiKVTxnCmdHistogram` metric.
Before
After
> metric: seperate source for txn cmd

- internal/locate/region_cache.go
Support read region without block, returns valid region when cache hit, and returns nil when cache miss or invalid.
> region_cache: support non-block read region

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request.go
- tikv/region.go
- tikvrpc/endpoint.go
1. Add `LabelFilter` for `getTiFlashRPCContext`,  `GetTiFlashStores()` and `GetAllValidTiFlashStores`
> region_cache: support <engine_role, write> for disaggregated tiflash

- go.mod
- go.sum
- integration_tests/go.mod
- integration_tests/go.sum
- internal/apicodec/codec.go
- internal/locate/region_request_test.go
- tikvrpc/tikvrpc.go
> attach keyspace_id for manual compact request

- internal/client/client_interceptor.go
Currently we support to config the default resource group, relative https://github.com/pingcap/tidb/pull/41606. after remove resource group, we can see the metrics:
> resource_control: consider default as a normal group

- metrics/shortcuts.go
The `TxnWriteSizeHistogram` shortcuts should use `TiKVTxnWriteSizeHistogram` objects.
> metric: fix the incorrect txn size metric usages

- integration_tests/2pc_test.go
- txnkv/transaction/2pc.go
- txnkv/transaction/txn.go
This is a part of hotfix for https://github.com/pingcap/tidb/issues/28011 . It allow us do lock->put optimization without touching membuf.
> txnkv: add new API for lock->put optimization

- txnkv/transaction/txn.go
Porting https://github.com/tikv/client-go/pull/749 to the version used by tidb 7.0
> [tidb-7.0] Add exitAggressiveLockingIfInapplicable function and call within mutex of lockKeys

- integration_tests/2pc_test.go
- txnkv/transaction/2pc.go
#748 only works for select-for-update, lock->put optimization should also works for [update-non-index-column](https://github.com/pingcap/tidb/issues/25659).
> txnkv: convert LOCK on untouched kv into PUT

- integration_tests/2pc_test.go
- txnkv/transaction/2pc.go
Let
- k be the locked key that might be converted to PUT
- v be the value from membuf
- v' be the value from lockedKV
When IsUnnecessaryKeyValue(k, v) is true, we require v = v' when doing lock->put optimization, however it's not true because v has a tail untouched flag. So this PR tries to relex the value check.
> txnkv: relax value check on lock->put untouched kv

- internal/apicodec/codec.go
- internal/apicodec/codec_v1.go
- internal/apicodec/codec_v1_test.go
- internal/apicodec/codec_v2.go
- internal/apicodec/codec_v2_test.go
- internal/locate/pd_codec.go
This pull request decodes the region bucket key by mapping them into the keyspace range.
If the bucket key is in the keyspace, then decode it as usual, otherwise map it as `nil`.
> fix api v2 decode of region bucket's keys

- metrics/metrics.go
- txnkv/transaction/2pc.go
There is only metric for txn heartbeat duration, add a metric for the txn ttl lifetime, which may easy for us to know how long the lock to hold by a transaction.
> metrics: add txn ttl lifetime

- txnkv/transaction/2pc.go
It helps us identify the source of the error when investigating issues.
> log: print log if the assertion error is generated from client-go

- tikv/test_probe.go
Modify the name in the comment from "KVSTore" to "KVStore" match the type name.
> doc(tikv/test_probe.go) fix case typo in comment.

- internal/locate/region_request.go
- metrics/metrics.go
- metrics/shortcuts.go
Add the traffic metrics for stale-read, this tells the hit ratio and traffics produced by stale-read miss.
The metrics example:
Before 15:15, the stale-read hit ratio is high, and after 15:15, there are over 80% stale-read misses.
> add metrics for stale-read traffic

- txnkv/transaction/txn.go
> txn: fix goroutine leak

- internal/apicodec/codec_v2.go
This pull request encodes `coprocessor.StoreBatchTask` to support batch cop task in TiKV while enabling API v2.
> encode store batch tasks

- integration_tests/prewrite_test.go
- tikv/kv_test.go
need to enable failpoint before SetupTest
> fix TestRURuntimeStatsCleanUp

- integration_tests/resource_group_test.go
- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
The resource group name is mistakenly set in https://github.com/tikv/client-go/pull/772
> Fix wrong resource group name for some requests

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Ref pingcap/tidb#43481
Backport #765 to tidb-6.5
> avoid dataIsNotReady error while retrying stale read on the leader(#765)

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Ref pingcap/tidb#43673
Currently the flashback doesn't wait followers before responsing and continue workload, this PR handles such failure requests and redirect them to leader.
> Fallback to leader read when replica read meets flashback-in-progress error

- integration_tests/pd_api_test.go
- integration_tests/raw/api_test.go
- integration_tests/ticlient_test.go
- internal/resourcecontrol/resource_control.go
- oracle/oracle.go
- tikv/kv.go
- tikv/test_util.go
- util/pd.go
- util/pd_test.go
Close #795
after https://github.com/tikv/pd/pull/6413 merged, We can replace resolved-ts's current implementation in client-go
- support api mechanism to pd
- support api to get store min resolved ts
> pd http: support api to get store min resolved ts 

- integration_tests/lock_test.go
Ref: https://github.com/pingcap/tidb/issues/43243
As merging the PR https://github.com/tikv/client-go/pull/777 updates the TiDB referenced by intergration tests which then includes the change https://github.com/pingcap/tidb/pull/43397 , the test TestBatchResolveLocks  now can successfully run on unistore, whose implementation of ScanLock has been fixed.
> Do not skip TestBatchResolveLocks for unistore

- internal/locate/region_request.go
- internal/locate/region_request_test.go
Ref: pingcap/tiflash#7491
In disaggregated-mode(tiflash write-node), we only count 1 replica for tiflash to calculate 'WRU', no matter how many tiflash write-nodes there are.
> Count only one tiflash replica in disaggregated mode.

- internal/apicodec/codec_v2.go
> [CodecV2] cache keyspaceID when creating codecV2

- internal/locate/region_request.go
- metrics/metrics.go
- metrics/shortcuts.go
- tikvrpc/tikvrpc.go
- txnkv/txnsnapshot/snapshot.go
> Backport the stale read optimizations to 6.5

- .golangci.yml
- integration_tests/lock_test.go
- tikv/test_probe.go
- txnkv/txnlock/lock_resolver.go
Cherry-picks https://github.com/tikv/client-go/pull/794 to tidb-6.5 branch.
Ref: https://github.com/pingcap/tidb/issues/43243
> (6.5) lock_resolver: handle pessimistic locks in BatchResolveLocks (#794)

- internal/client/client_batch.go
> client_batch: tiny optimize

- internal/mockstore/mocktikv/pd.go
ref https://github.com/pingcap/tidb/pull/44339, it creates resource manager client in domain, so it use mock pd client from client-go.
> mock: impl resource manager get default resource group

- internal/client/client_interceptor.go
- tikv/kv.go
ref https://github.com/pingcap/tidb/issues/44818
https://github.com/pingcap/tidb/pull/44819 is another attempt to fix the race but the test still failed https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/26946/display/redirect.
while in theory, we can init the `ResourceControlInterceptor` once when the server is bootstrapped. But due to some implementation restriction, it's hard to do so in tidb and the current code can case data race though the data race is harmless. 
So this PR changes the type to atomic ptr for simplicity.
> make ResourceControlInterceptor atomic

- txnkv/txnlock/lock_resolver.go
fix https://github.com/pingcap/tidb/issues/44822 , after this PR tidb can pass the test.
> lock_resolver: let resolve lock timeout properly

- error/error.go
- integration_tests/store_test.go
- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_test.go
>  reload region cache when store is resolved from invalid status (#843)

- internal/locate/region_request.go
- internal/locate/region_request_test.go
close https://github.com/pingcap/tidb/issues/44990
> *: refine non-global stale-read request retry logic

- .github/workflows/integration.yml
- .github/workflows/test.yml
- .golangci.yml
- integration_tests/lock_test.go
- tikv/test_probe.go
- txnkv/txnlock/lock_resolver.go
Ref: https://github.com/pingcap/tidb/issues/43243
Cherry-picks #794 to tidb-6.1 branch
> (6.1) lock_resolver: handle pessimistic locks in BatchResolveLocks (#794)

- internal/locate/region_cache.go
Close #860 . Add `StartKey` and `EndKey` info to error when client returns 'PD returned no region'
> client-go: add some key range info to error when PD returned no region

- integration_tests/lock_test.go
- internal/locate/region_request.go
- tikv/test_probe.go
- txnkv/transaction/txn.go
- txnkv/txnlock/lock_resolver.go
Ref https://github.com/pingcap/tidb/issues/45134
The problem is that `BatchResolveLock` calls `resolvePessimsticLock` without calling `getTxnStatus`, but `resolvePessimsticLock` assumes `getTxnStatus` (in which `CheckTxnStatus` RPC is called) is done so it doesn't do anything to primary pessimistic lock. This may result in residue pessimistic locks in some rare cases.
This PR moves `resolvePessimsticLock` calling to after `getTxnStatus` to avoid the problem.
> Fix the issue that primary pessimistic lock may be left not cleared after GC

- integration_tests/lock_test.go
- tikv/test_probe.go
- txnkv/transaction/txn.go
- txnkv/txnlock/lock_resolver.go
Cherry-picks https://github.com/tikv/client-go/pull/866 to tidb-6.1 branch
Ref https://github.com/pingcap/tidb/issues/45134
The problem is that BatchResolveLock calls resolvePessimsticLock without calling getTxnStatus, but resolvePessimsticLock assumes getTxnStatus (in which CheckTxnStatus RPC is called) is done so it doesn't do anything to primary pessimistic lock. This may result in residue pessimistic locks in some rare cases.
This PR moves resolvePessimsticLock calling to after getTxnStatus to avoid the problem.
> (6.1)  Fix the issue that primary pessimistic lock may be left not cleared after GC (#866)

- integration_tests/lock_test.go
- tikv/test_probe.go
- txnkv/transaction/txn.go
- txnkv/txnlock/lock_resolver.go
Cherry-picks https://github.com/tikv/client-go/pull/866 to tidb-6.5 branch
Ref https://github.com/pingcap/tidb/issues/45134
The problem is that BatchResolveLock calls resolvePessimsticLock without calling getTxnStatus, but resolvePessimsticLock assumes getTxnStatus (in which CheckTxnStatus RPC is called) is done so it doesn't do anything to primary pessimistic lock. This may result in residue pessimistic locks in some rare cases.
This PR moves resolvePessimsticLock calling to after getTxnStatus to avoid the problem.
> (6.5) Fix the issue that primary pessimistic lock may be left not cleared after GC (#866)

- integration_tests/lock_test.go
- tikv/test_probe.go
- txnkv/transaction/txn.go
- txnkv/txnlock/lock_resolver.go
Cherry-picks https://github.com/tikv/client-go/pull/866 to tidb-7.1 branch
Ref https://github.com/pingcap/tidb/issues/45134
The problem is that BatchResolveLock calls resolvePessimsticLock without calling getTxnStatus, but resolvePessimsticLock assumes getTxnStatus (in which CheckTxnStatus RPC is called) is done so it doesn't do anything to primary pessimistic lock. This may result in residue pessimistic locks in some rare cases.
This PR moves resolvePessimsticLock calling to after getTxnStatus to avoid the problem.
> (7.1) Fix the issue that primary pessimistic lock may be left not cleared after GC (#866)

- tikvrpc/interceptor/interceptor.go
- txnkv/transaction/txn.go
- util/request_source.go
- util/request_source_test.go
if use
```
set @tidb_request_source_type='lightling'
select count(*) from t;
```
the request source field will like:
```
external_Select_lightning
```
> add explicit request source type to label the external request like lightning/br

- internal/locate/region_request.go
- internal/locate/region_request_test.go
cherry-pick https://github.com/tikv/client-go/pull/851
> *: refine non-global stale-read request retry logic (#851)

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
As pingcap/tidb#45297 reports, TiKV may report `mismatch peer id` error, currently the client-go doesn't handle such error, this PR checks this error and invalidate the region cache when receiving this error.
> handle `mismatch peer id` region error

- internal/locate/region_request.go
- metrics/metrics.go
- metrics/shortcuts.go
The stale read ops metric is not right for some time. I found this issue when test stale read with reload all tikv node.
This PR is base on https://github.com/tikv/client-go/pull/877
after fixed in this PR, the `stale read ops`, `stale read req ops` and `stale read traffic` metrics is like following when reload all tikv:
> *: fix stale read ops metric

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
See the comment, the error message contains the code path, so it's not able to match it by prefix.
> Match error message correctly

- internal/client/client_interceptor.go
- internal/resourcecontrol/resource_control.go
- internal/resourcecontrol/resource_control_test.go
- tikvrpc/interceptor/interceptor.go
- txnkv/transaction/txn.go
- util/request_source.go
- util/request_source_test.go
In tidb, the source request will be tiny but urgent. we can consider skip it by resource control
```
const (
// InternalTxnOthers is the type of requests that consume low resources.
// This reduces the size of metrics.
InternalTxnOthers = util.InternalTxnOthers
// InternalTxnBootstrap is the type of TiDB bootstrap txns.
InternalTxnBootstrap = InternalTxnOthers
// InternalTxnMeta is the type of the miscellaneous meta usage.
InternalTxnMeta = util.InternalTxnMeta ==> util.InternalTxnOthers
// InternalTxnCacheTable is the type of cache table usage.
InternalTxnCacheTable = InternalTxnOthers
// InternalTxnBindInfo is the type of bind info txn.
InternalTxnBindInfo = InternalTxnOthers
// InternalTxnSysVar is the type of sys var txn.
InternalTxnSysVar = InternalTxnOthers
// InternalTxnTelemetry …
```
> resource_control: bypass some internal urgent request

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
cherry-pick https://github.com/tikv/client-go/pull/888
> handle `mismatch peer id` region error #885

- internal/resourcecontrol/resource_control.go
- internal/resourcecontrol/resource_control_test.go
> resourcecontrol: fix nil pointer

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
close #898
After stop 1 tikv-server, some region replicas are marked by `replica.isEpochStale` is `true`. Then `accessFollower` won't choose the replica anymore.
But when TiDB GC leader start to running GC, it will reload [all region](https://github.com/tikv/client-go/blob/c7e214f2c32b47b9c5a1e1f50a313cb678cd83da/txnkv/rangetask/range_task.go#L191), then all region replicas epoch will be update, which means all region replica's `isEpochStale` will change to `false`. Then `accessFollower` may choose the replica which in down tikv-server. Then TiDB may send kv request to down tikv-server will receive `context deadline exceeded` error and re-send kv request to the region leader. This is what causes slow queries.
In short,  `accessFollower` need to check the replica's store `LivenessState` …
> fix unexpected slow query during GC running after stop 1 tikv-server

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
> fix unexpected slow query during GC running after stop 1 tikv-server (#899)

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Ref: https://github.com/tikv/client-go/issues/902
Allow only another extra leader retry when processing the `DataIsNotReady` error.
> Resume the max retry check for stale read processing

- txnkv/txnsnapshot/snapshot.go
Issue Number: https://github.com/pingcap/tidb/issues/45380
This PR implements the following subtask, which is an interface between `tidb` and `client-go`  for this feature.
- Add set interface SetKVReadTimeout and get interface GetKVReadTimeout for KVSnapshot.
> define KVSnapshot#readTimeout field

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Fallback to follower when leader is busy.
Inject data-is-not-ready for stale read and server-is-busy for leader, so fallback to leader will be stucked.
With this patch, server-is-busy on leader will try followers.
> fallback to follower when leader is busy

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/retry/backoff.go
- kv/store_vars.go
Add more logs for diagnose.
Here some log example:
```log
[2023/07/27 16:54:36.207 +08:00] [WARN] [region_request.go:615] ["unable to find stores with given labels"] [region=3021] [leader-invalid=false] [labels="[{\"key\":\"zone\",\"value\":\"z99\"}]"]
[2023/07/27 16:54:36.309 +08:00] [INFO] [region_cache.go:2633] ["change store resolve state"] [store=4] [addr=10.0.1.9:21161] [from=resolved] [to=needCheck] [liveness-state=unreachable]
[2023/07/27 16:54:57.687 +08:00] [WARN] [backoff.go:172] ["regionMiss backoffer.maxSleep 40000ms is exceeded, errors:\nregion_id:3021, region_ver:71, store_type:tikv, peer_addr:, error:epoch_not_match:<>  at 2023-07-27T16:54:56.183288+08:00\nregion_id:3021, region_ver:71, store_type:tikv, peer_addr:, error:epoch_not_match:<>  at …
```
> add more log for diagnose

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request_state_test.go
- internal/mockstore/mocktikv/cluster.go
- internal/mockstore/mocktikv/cluster_manipulate.go
This PR add the selector replica test for stale read, cover the most possible errors, and fix the bug the test finds:
Fixes:
- when fallback to followers from leader, stale-read flag should be removed.
- in some cases, the fallback to follower not work.
- when using stale read, allow async reload region when leader is exhausted, because leader may just be unavailable for a while, and the late update of region info won't affect stale read processing.
> add region cache state test & fix some issues of replica selector

- .github/workflows/compatibility.yml
- .github/workflows/integration.yml
- .github/workflows/test.yml
- internal/client/main_test.go
tidb use go1.21 after https://github.com/pingcap/tidb/pull/45923
> ci: update go version

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
> fallback to follower when leader is busy (#916)

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/retry/backoff.go
- kv/store_vars.go
> add more log for diagnose (#915)

- integration_tests/pd_api_test.go
- internal/locate/region_request_state_test.go
- tikv/kv.go
- util/pd.go
1. api interface
Nowadays we have 2 api interfaces for obtaining min resolved ts
- /pd/api/v1/min-resolved-ts: obtain cluster's min resolved ts
- /pd/api/v1/min-resolved-ts/{store_id}: obtain each store's min resolved ts
For client-go's updateSafeTS, we call `approach II` for each store, which is not necessary to call API so many times 
We can use the `approach I` to get cluster's min resolved ts when `@@txn_scope` is `global`
2. avoid using kv request reason:
if TiDB failed to connect a TiKV store to fetch the latest resolved_ts, it will remain the out-of-dated value until the TiKV comes back, though PD will mark the store as unavailable and keep updating the minimal resolved_ts with other TiKV stores. We may need to keep these two behaviors the same or unify them.
judge `@@txn_scope` …
> min-resolved-ts: check dc label

- internal/locate/region_request.go
Recently, we made some changes to the selector states, the `tryFollower` is not only used as a fallback state of `accessKnownLeader`, this PR keeps the compatibility of `tryFollower`'s requests.
Before the changes we made:
`accessKnownLeader` -> `tryFollower` -> switch leader when success, and the flag `KVContext.ReplicaRead` is always false here.
Now there is another path lead to `tryFollower` state:
`accessFollower` -> `tryFollower`, in this case, `KVContext.ReplicaRead` is set to true in `tryFollower` state.
To make the behavior compatible with earlier versions, we need to set a flag for the `accessKnownLeader` -> `tryFollower` path, and that's `fromKnownLeader`. It's renamed from `fromOnNotLeader` for better semantic.
cc @crazycs520
> use leader read when `tryFollower` is fallback from `accessKnownLeader`

- internal/client/client_batch.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- txnkv/txnsnapshot/snapshot.go
> use tidb_kv_read_timeout as first kv request timeout (#919)

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
1. Refactor and group the logging-related logic into `RegionRequestSender` and `replicaSelector`.
2. Split the `totalErros` into details for `NotLeader` error responses, 
from
```
[total-region-errors="not_leader-nil:3"]
```
```
[Prefix: target peer id]-not_leader-[Suffix: Leader information in the returned error and nil if no leader]
[total-region-errors="6-not_leader-nil:1, 4-not_leader-nil:1, 5-not_leader-nil:1"]
```
> log: group replica selector logging and split not leader errors

- internal/locate/region_request.go
In past, it report unknown error if met `bucket verison not match `
> metrics: add bucket version not match metrics

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
As https://github.com/tikv/client-go/pull/953#issuecomment-1708749115 says, the format modified by #953 is not compatible with TiKV, this PR set the request source as the last section, so that TiKV can handle it correctly.
> request_source: set the request source at the last section

- internal/client/client_batch.go
- internal/locate/region_cache.go
- util/misc.go
close #966
Following is a tiny test:
Before this PR:
```go
func TestLog(t *testing.T) {
defer func() {
if r := recover(); r != nil {
logutil.BgLogger().Warn("recover panic", zap.Reflect("r", r))
}
}()
s := []int{}
s[0] = 1
}
```
You will get the following log:
```log
[2023/09/11 14:36:19.797 +08:00] [WARN] [client_test.go:729] ["recover panic"] [r={}]
```
This PR, use `zap.Any` instead of `zap.Reflect`, You will get the following log:
```log
[2023/09/11 14:36:49.106 +08:00] [WARN] [client_test.go:729] ["recover panic"] [r="runtime error: index out of range [0] with length 0"]
```
> *: refine panic log

- internal/client/client_batch.go
- internal/locate/region_request.go
before:
`
[2023/09/08 15:03:03.275 +08:00] [INFO] [region_request.go:1513] ["throwing pseudo region error due to no replica available"] [req-ts=444112978761220102] [req-type=Cop] [region="{ region id: /pd-ctl , ver: 483, confVer: 83 }"] [replica-read-type=leader] [stale-read=false] [request-sender="{replicaSelector: replicaSelector{selectorStateStr: tryFollower, cacheRegionIsValid: true, replicaStatus: [peer: 35611558, store: 13, isEpochStale: false, attempts: 1, replica-epoch: 0, store-epoch: 0, store-state: resolved, store-liveness-state: reachable peer: 35611559, store: 28, isEpochStale: false, attempts: 1, replica-epoch: 0, store-epoch: 0, store-state: resolved, store-liveness-state: reachable peer: 35611560, store: 31, isEpochStale: false, attempts: 1, replica-epoch: 0, store-epoch: …
> Add log for detail rpc failed reason

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
close #970
Do the same test in #970 
**Before this PR**
The following are related metrics, some of metrics here are not as expected:
- Too much failed query in TiDB `192.168.78.2`, which cause by execution timeout.
**This PR**
- TiDB `192.168.78.2` doesn't have any failed query which execution timeout now, and doesn't have backoff too.
- TIDB `192.168.78.2` has a low QPS because each of the stale-read queries will timeout (100ms) first and then retry to succeed, and it only has 15 connections executing requests.
> *: try follower when stale read request timeout

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
> *: try follower when stale read request timeout (#969)

- internal/client/client_fail_test.go
- internal/client/client_test.go
- internal/client/mock_server/mock_tikv_service.go
- internal/locate/region_request.go
- internal/locate/region_request_test.go
> *: fix issue of configure kv timeout not work when disable batch client

- internal/client/client.go
- internal/client/client_batch.go
- metrics/metrics.go
close #974
Do same test in issue #974, the related metric in this PR is following:
The QPS is much more stable
> *: fix batch-client wait too long and add some metrics

- internal/locate/region_cache.go
The annotation of LoadRegionsInKeyRange seems to be misleading.
I think it is better to fix it. 
It once wasts time of me when i am troubleshooting a tidb bug.  
As issue #924 describe.
> fix misleading annotation of LoadRegionsInKeyRange

- internal/locate/region_cache.go
- internal/locate/region_request.go
before:
`
[2023/09/21 14:35:50.702 +08:00] [INFO] [region_request.go:1522] ["throwing pseudo region error due to no replica available"] [conn=1887493856] [session_alias=] [req-ts=444406212641423730] [req-type=Cop] [region="{ region id: 186911575, ver: 832, confVer: 407 }"] [replica-read-type=leader] [stale-read=false] [request-sender="{rpcError:<nil>,replicaSelector: replicaSelector{selectorStateStr: nil, cacheRegionIsValid: unknown, replicaStatus: []}}"] [retry-times=0] [total-backoff-ms=0] [total-backoff-times=0] [max-exec-timeout-ms=60000] [total-region-errors=]
`
after
`
[2023/09/21 19:07:34.787 +08:00] [INFO] [region_request.go:1533] ["throwing pseudo region error due to no replica available"] [conn=3749708330] [session_alias=] [req-ts=444411269215682567] [req-type=Cop] [region="{ …
> add replica selector init failed reason 

- .github/workflows/integration.yml
- .github/workflows/test.yml
- error/error.go
- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_state_test.go
- internal/locate/region_request_test.go
- internal/mockstore/mocktikv/cluster.go
- internal/mockstore/mocktikv/cluster_manipulate.go
Cherry pick #843, #923, #911, #942 to 7.1 branch.
- Fix the inbalance issue of replica read request when store is down and up by reloading the latest region in background.
- For replica read, when leader is busy, fallback to follower.
- Set max retry for replica read.
- Add test of replica selector's state for stale read.
> Cherry pick some patches to 7.1

- metrics/metrics.go
Close https://github.com/pingcap/tidb/issues/47397.
> metrics: make upper limit of RPC latency larger

- integration_tests/pd_api_test.go
- tikv/kv.go
close #991 
The core question is the getter 
- we introduce `PD API` to not execute `go func which for KV request`, resulting in not updating `safeTSMap`. 		 
- `updateMinSafeTS` relies on  `safeTSMap` which makes sense(because actually, we can call `updateMinSafeTS` to `kvReuqestUpdater`[to indicate func base]).
- And we need to update `minsafeTS` to make sure when API fails we can fall back to the original way which is by kv request.
- But the core problem is:  **`updateMinSafeTS` will return `maxUnit64` when the first kv request returns 0 and then although `PD API` returns correctly[maybe kv is not initialized], TS can not change `maxUnit64`.**
- to resolve this question, we need to regard `maxUnit64` as 0 which means there is an initial state.
> min-safe-ts: fix MinSafeTS might be set to MaxUint64 permanently

- internal/locate/region_request3_test.go
- internal/locate/region_request_state_test.go
- internal/locate/region_request_test.go
- tikvrpc/tikvrpc.go
- txnkv/txnsnapshot/snapshot.go
Simple refactor to make the function name more clear.
> refactor the func name to make it clear

- internal/locate/region_request.go
This pr is a bugfix pr, used to fix the `panic` issue when trying to record Store.SlownessStat if `rpcCtx.Store == nil`.
Related issue: https://github.com/pingcap/tidb/issues/47531
> bugfix: fix invalid nil pointer when trying to record Store.SlownessStat.

- internal/retry/backoff.go
- internal/retry/backoff_test.go
- internal/retry/config.go
Ref: https://github.com/tikv/client-go/issues/1001
Try to add retry limit for excluded backoff type to avoid infinite retry.
> add retry limit for excluded backoff type to avoid infinite retry

- internal/client/client_batch.go
- internal/locate/region_cache.go
- internal/locate/region_request_test.go
- tikvrpc/tikvrpc.go
- util/misc.go
> Fix batch client batchSendLoop panic (#1021)

- internal/client/client_batch.go
- metrics/metrics.go
This reverts commit 1a442527792995593354e6c9298def137446a4e0.
Since #996 brings some performance regression, At present, I have no good way to avoid it, and in a hurry to release, so I revert this PR first.
TiDB workload: select_random_points
before:
after:
> Revert "*: add metrics for batch client (#996)"

- .github/workflows/compatibility.yml
- internal/client/client_interceptor.go
- internal/client/client_interceptor_test.go
- tikv/kv.go
- tikv/kv_test.go
- util/execdetails.go
To collect all query RU consumption into statement log, ref https://github.com/tidbcloud/tidb-cse/pull/678
> collecting the RU information by pasing point through context.Value

- txnkv/transaction/2pc.go
cloud-storage-engine has larger region size 512MB, we don't want to split regions into 32MB size on large transaction write.
> increase large transaction preSplitSizeThreashold

- oracle/oracles/export_test.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
Cherry pick #1054 to tidb-7.1 branch, which fix the monotonic issue of stale TSO.
> tso: merge lastTS and lastArrivalTS into an atomic pointer (#1054)

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_test.go
close https://github.com/pingcap/tidb/issues/49254
> region_cache: no need to metrics when inserting for scan regions

- config/security.go
after upgrading the GRPC 1.60, it changed some behaviors.
so we have to set the tls.MinVersion
> *: set default tls.MinVersion as tls.VersionTLS10

- config/retry/backoff.go
- integration_tests/2pc_test.go
- internal/client/retry/backoff.go
- internal/locate/region_request.go
- kv/variables.go
Previously the kill signal was checked against `1`, however TiDB uses non-zero values to indicate a kill signal.
> fix: check kill signal against 0

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
> Fix the issue that leader change with nea leader info cause invalidStore state and lead to unnecessary backoff

- config/security.go
ref https://github.com/pingcap/tidb/issues/36036
TLSv1.1 and older should not be used by default.
https://www.rfc-editor.org/rfc/rfc8996.html#name-do-not-use-tls-11
https://dev.mysql.com/worklog/task/?id=14519
https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html#encrypted-connection-supported-protocols
> Change MinTLSVersion to TLSv1.2

- internal/client/client.go
- internal/locate/region_request.go
Close #1120, https://github.com/tidbcloud/cloud-storage-engine/issues/1264
Close connection when get gRPC error as `Code.Canceled`, as the error would be caused by keep alive timeout. Then the next retry will try to establish the connection again. Otherwise, as underlying gRPC client has been canceled, we will keep get the same error.
> Close connection when get gRPC error Code.Canceled

- internal/locate/main_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Ref https://github.com/pingcap/tidb/issues/50432
> Check time spent on attempting RPC to avoid spending too much time on retrying

- config/retry/backoff.go
- integration_tests/2pc_test.go
- internal/client/retry/backoff.go
- internal/locate/region_request.go
- kv/variables.go
Temporarily revert #1102 to avoid test failures on TiDB repo.
This would be fixed by #1124 later.
> Revert "fix: check kill signal against 0 (#1102)"

- internal/locate/main_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Cherry-pick #1117 to 6.5 branch
> Check time spent on attempting RPC to avoid spending too much time on retrying (#1117)

- internal/locate/main_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
This reverts commit 062f4c9e3dfa1e9f98c299ae19e72375b7f72ce1
which is merged in a rush before it's considered risky to merge in a rush.
> Revert "Check time spent on attempting RPC to avoid spending too much time on retrying (#1117) (#1131)

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request3_test.go
- internal/retry/backoff_test.go
- rawkv/rawkv_test.go
> fix the issue that health check may set liveness wrongly (#1127)

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_state_test.go
- internal/locate/region_request_test.go
- internal/locate/sorted_btree.go
- metrics/metrics.go
- tikv/region.go
Ref https://github.com/tikv/client-go/pull/1122#discussion_r1469009792 and #1104 .
This PR tries to address https://github.com/tikv/client-go/pull/1122#discussion_r1469009792 by introducing a random jitter to region cache TTL.
To observe the reason of region reloading, the methods for searching cached regions are refactored.
> introduce a random jitter to region cache ttl

- error/error.go
- integration_tests/2pc_test.go
- internal/locate/region_request.go
- internal/retry/backoff.go
- kv/variables.go
- txnkv/transaction/2pc.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/txn.go
Cherry picking #1084 and #1124
> [Cherry-pick tidb-7.5] Check kill signals

- oracle/oracle.go
- oracle/oracles/export_test.go
- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
- tikv/kv.go
- tikv/test_probe.go
Closes #1154 and is the first half of https://github.com/pingcap/tidb/issues/51081. 
Adds new function `SetLowResolutionTimestampUpdateInterval(time.Duration) error` to the Oracle interface and implements it in `pdOracle` to control how often timestamps are refreshed in the local cache. Default behavior remaining unchanged at 2s.
> Configurable low res tso update interval (#1154)

- config/retry/config.go
- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_state_test.go
- internal/locate/region_request_test.go
- internal/locate/replica_selector_test.go
- internal/locate/slow_score.go
> stale read request shoudn't retry leader if leader is already tried

- internal/unionstore/pipelined_memdb.go
- internal/unionstore/pipelined_memdb_test.go
- txnkv/txnsnapshot/snapshot.go
Add failpoint interface to adjusting the flush options for pipelined memdb.
> adjust parameter for pipelined memdb by failpoint

- integration_tests/pipelined_memdb_test.go
- internal/client/client_collapse.go
- txnkv/transaction/pipelined_flush.go
The `ResolveLock` requests may race because it's handled by another goroutine, this PR fix it by a shallow copy before sending it.
```text
WARNING: DATA RACE
Write at 0x00c0005270dc by goroutine 46:
github.com/tikv/client-go/v2/internal/locate.(*RegionRequestSender).SendReqCtx()
/Users/you06/workspace/go/src/github.com/tikv/client-go/internal/locate/region_request.go:1563 +0x1bb8
github.com/tikv/client-go/v2/internal/locate.(*RegionRequestSender).SendReq()
/Users/you06/workspace/go/src/github.com/tikv/client-go/internal/locate/region_request.go:247 +0x19c
github.com/tikv/client-go/v2/tikv.(*KVStore).SendReq()
/Users/you06/workspace/go/src/github.com/tikv/client-go/tikv/kv.go:524 +0x170
integration_tests_test.(*testPipelinedMemDBSuite).TestResolveLockRace() …
```
> fix data race when collapsing ResolveLockRequest

- error/error.go
- go.mod
- go.sum
- internal/unionstore/pipelined_memdb.go
This is to provide the value for TiDB to generate the corresponding duplicate entry error. 
For vanilla memdb, the value was obtained by memdb.SelectValue(). 
For pipelined memdb, the `flushingMemDB` will be cleared once an error returned. So we choose to retain the value in the error struct.
> P-DML: for AlreadyExist error, attach the value from flushingMemDB

- .github/workflows/test.yml
- txnkv/transaction/2pc.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/prewrite.go
ref https://github.com/tikv/tikv/issues/16291
Pipelined txn tends to run long. The default max TTL of 1 hour might not be enough.
> feat: pipelined dml has its own max-txn-ttl of 24 hours

- internal/client/client_batch.go
- internal/client/client_test.go
- internal/client/main_test.go
Close #1225.
Data race issue #1222 should be fix in PR #1219.
> fix issue that no available connections cause by concurrency request limit bug

- config/client.go
- config/config.go
- internal/locate/replica_selector.go
- internal/locate/replica_selector_test.go
Add `TiKVClient .EnableReplicaSelectorV2` config and enable by default.
`TiKVClient.EnableReplicaSelectorV2` config should be removed after the new replica-selector-v2 is stable.
```toml
[tikv-client]
enable-replica-selector-v2 = true
```
> enable replica-selector-v2 by default

- internal/unionstore/pipelined_memdb.go
ref https://github.com/tikv/tikv/issues/16291
So that its memory usage can be tracked.
> Implement Mem() and SetMemoryFootprintChangeHook() for PipelinedMemDB

- internal/unionstore/pipelined_memdb.go
> fix: check mem != nil before calling Mem()

- config/client.go
- internal/client/client.go
- internal/locate/region_cache.go
cherry-pick https://github.com/tikv/client-go/pull/1239 to 6.1
> [Cherry-pick-to-6.1] Add grpc window size config and change the default value

- config/client.go
- internal/client/client.go
- internal/locate/region_cache.go
cherry-pick https://github.com/tikv/client-go/pull/1239 to 6.5
> [Cherry-pick-to-6.5] Add grpc window size config and change the default value

- util/execdetails.go
The kv read wall time which is the time consumed in tikv executors is not printted in the result. 
It is helpful to check time consumed in the tikv next operations, for example processing column with larger values.
> cop: add kv read wall time to print result

- integration_tests/pd_api_test.go
- tikv/kv.go
- tikv/kv_test.go
Try to fix #1249
with this PR, no stale read miss after rolling restart tikv:
without this fix:
> tikv: ensure safe-ts won't be max uint64

- internal/client/client_batch.go
- internal/client/client_test.go
close #1222  , https://github.com/pingcap/tidb/issues/51728
> *: fix data race that may cause panic and concurrency request limit bug

- integration_tests/snapshot_test.go
- util/execdetails.go
Ref: https://github.com/pingcap/tidb/pull/52146 and https://github.com/pingcap/tidb/issues/28937
The `Merge`(https://github.com/tikv/client-go/pull/1248) of `TimeDetail` could be called concurrently, fix the data race.
> cop: fix time detail merge

- util/execdetails.go
- util/misc_test.go
Before this PR, following is unexpected:
```go
time_detail: {, tikv_wall_time: 500ms}
```
> refine timedetail string

- internal/locate/region_cache.go
- internal/locate/store_cache.go
Try to fix https://github.com/pingcap/tidb/issues/46602 .
`GetTiFlashStores` would return unresolved stores, which causes mpp probe keep checking tomebstone stores. `RegionCache` exports some methods for listing stores, like `GetAllStores`. There should/better be a contract that those methods do not return unresolved stores. Note that `GetTiFlashComputeStores` may still returns unresolved stores, however, the entire store list will be reloaded once invalidate method get called, that is, it's users' responsibility to reload tiflash compute stores.
> region_cache: filter out unresolved stores when GetTiFlashStores

- internal/locate/replica_selector.go
- internal/locate/replica_selector_test.go
close #1274
Issue description: 1 tikv down will cause qps drop and did not recover for a long time, which is unexpected.
```sh
sysbench --config-file=config oltp_read_only --tables=2 --table-size=1000000 run
```
After run a while, stop 1 tikv node.
**Before This PR**
TiDB Metrics:
- 13:40:00 stop 1 tikv
- 13:44:00 restart the down tikv.
TiKV metrics:
**This PR**
- 13:51:00 stop 1 tikv
- 13:54:00 restart the down tikv.
> fix bug of not invalidate store when tikv store is down in replica-selector-v2 with enable forwarding

- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/txn.go
Self-explained by the comment.
> Allow setting session id of KVTxn

- integration_tests/range_task_test.go
- tikv/gc.go
- txnkv/rangetask/delete_range.go
- txnkv/rangetask/range_task.go
- txnkv/transaction/pipelined_flush.go
`name` is used in both metrics and logs. We separate name and identifier to avoid messy metrics and pertain useful logs.
> Distinguish identifier and name in task runner

- tikv/kv.go
- tikv/kv_test.go
fix https://github.com/tikv/client-go/issues/1276
> avoid calling setMinSafeTS with max u64

- integration_tests/safepoint_test.go
- integration_tests/snapshot_test.go
- integration_tests/store_test.go
- txnkv/txnsnapshot/snapshot.go
Now snapshot cache can only be generated by `snapshot.BatchGet` which doesn't optimize the case get the same key multi times in a txn.
This PR cache the result of `snapshot.Get` to optimize this case.
Test with sysbench point select, but wrap it in txn:
```
begin;
point select with same id n times;
commit;
```
|n|Before thisPR(txn/s)|With this PR(txn/s)|
|-|-|-|
|2|59029|68541|
|3|43032|57330|
|4|34583|49275|
> txn: cache result of snapshot.Get

- txnkv/transaction/txn_file.go
As there is already retry inside `SplitRegions` (see [`batchSendSingleRegion`](https://github.com/tikv/client-go/blob/tidb-cse-7.5/tikv/split_region.go#L170)), it's not necessary to retry in `preSplitTxnFileRegions`. Otherwise, when split regions failed due to, e.g., txn file lock, `preSplitTxnFileRegions` will cost very long time to finish.
The retry for `groupToBatches` should also be removed, as `LocateKey` has internal retry as well. See [`RegionCache::loadRegion`](https://github.com/tikv/client-go/blob/15f5f67f8a1fac098155aab2e51d25df7ff67f49/internal/locate/region_cache.go#L1644).
Remove retry for `preSplitTxnFileRegions`.
> txn-file: Remove retry of pre split regions

- internal/unionstore/pipelined_memdb.go
- internal/unionstore/pipelined_memdb_test.go
ref tikv/tikv#16291
By default, a pipelined-txn can use more than 1GB memory, most of which are consumed by memdb. 
Use `Mem()` as an estimate to more accurately control the total memory usage.
> Use Mem() instead of Size() to estimate pipelined-memdb size

- txnkv/transaction/txn_file.go
- txnkv/transaction/txn_file_test.go
- util/merge_ranges.go
- util/merge_ranges_test.go
- Asynchronously commit/rollback secondary keys.
- Rename `executeTxnFileAction` -> `executeTxnFileSlice`, `executeTxnFileActionWithRetry` -> `executeTxnFileSliceWithRetry`.
- Separate execution of primary batch from `executeTxnFileSlice` to `executeTxnFilePrimaryBatch`.
- Add `executeTxnFileAction`, execute primary batch (`executeTxnFilePrimaryBatch`) first, then execute secondaries synchronously/asynchronously according to `action.asyncExecuteSecondaries()`.
- Fill `Keys` of commit & rollback request to help detecting duplicated.
> txn-file: Asynchronously commit/rollback secondaries

- internal/logutil/log.go
- tikv/kv.go
- tikv/kv_test.go
https://github.com/tikv/client-go/pull/1277 introduce a regression: there might be a store whose safe ts is 0 for a long time, in this case, flashback will be blocked (ref: https://github.com/tikv/tikv/issues/13675). We should `setMinSafeTS(0)` only when all (NOT any) of `store.safe_ts = 0`.
> only set MinSafeTS to 0 when all stores' are 0

- txnkv/transaction/2pc.go
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/prewrite.go
close #595 
1 lock is enough for most of the cases.
> log: only log the first lock in every flush or prewrite response

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
https://github.com/tikv/client-go/pull/1122#discussion_r1469008167 here we introduce an issue: if a region is marked as NeedDelayedReload, then we try to reload it by id and return the new region directly without checking the range, which may cause `LocateKey` returns a wrong region when the region is just splitted. To fix this issue, we can:
1. always use `loadRegion` (by key)
2. check the range of the new region (returned by `loadRegionByID`), call `loadRegion` if it doesn't contain the key
Here we prefer the first solution for simplicity.
> region_cache: fix issue that LocateKey may returns a wrong region

- internal/locate/replica_selector_test.go
skip TestReplicaReadAccessPathByGenError because it's unstable and slow.
And the test will be removed in #1265
> skip TestReplicaReadAccessPathByGenError because it's unstable and slow

- internal/locate/region_request.go
Change some log level to reduce unnecessary log when DataIsNotReady.
And we don't rely on this log to diagnose problems.
> reduce unnecessary log when DataIsNotReady

- integration_tests/pipelined_memdb_test.go
- internal/unionstore/pipelined_memdb_test.go
- tikv/test_probe.go
- txnkv/transaction/2pc.go
- txnkv/transaction/txn.go
ref pingcap/tidb#52760, tikv/tikv#16291
Once the pipelined dml's ttl manager is stopped, fail the pipelined dml to avoid GC blocking and writing meaningless locks.
```sql
MySQL [test1]> insert into sbtest4_gc_max select * from sbtest4;
ERROR 1105 (HY000): ttl manager is closed
```
> txn: abort pipelined dml when pk rollback

- integration_tests/snapshot_test.go
- txnkv/txnsnapshot/snapshot.go
The snapshot version maxuint64 doesn't satisfy the total order of TSO, do not cache it to avoid anomaly of missing latest data.
> txn: do not cache value with snapshot version maxuint64

- integration_tests/snapshot_test.go
- txnkv/txnsnapshot/snapshot.go
cherry pick #1320 to tidb-8.1
The snapshot version maxuint64 doesn't satisfy the total order of TSO, do not cache it to avoid anomaly of missing latest data.
> txn: do not cache value with snapshot version maxuint64 (#1320)

- txnkv/transaction/commit.go
This is simply a defensive check. We don't expect it to happen.
> Check primary key when handling CommitTsExpired error

- integration_tests/pd_api_test.go
- internal/logutil/log.go
- tikv/kv.go
- tikv/kv_test.go
pick #1250 to tidb-7.5, also include #1277 & #1284.
> pick #1250 to tidb-7.5

- config/client.go
- kv/variables.go
- txnkv/transaction/txn.go
- txnkv/transaction/txn_file.go
- Add config item to specify minimum mutation size to use txn file
- Check `c.txnFileCtx.slice.len() > 0` when rollback on error. When the error happen before building txn chunks, the `slice` will be empty and rollback will panic.
- Use specified backoff for different step (build/prewrite/commit).
- Fix region error judgement in `executeTxnFileSlice`.
- Do not use txn file for internal commands, to avoid affect system tables or metadata in case txn file has some bugs. Specially handle TTL and DDL tasks laster.
> txn-file: Add config item to specify minimum mutation size to use txn file

- integration_tests/pipelined_memdb_test.go
- txnkv/transaction/2pc.go
Cherry pick #1329 to tidb-8.1 branch
ref https://github.com/tikv/tikv/issues/16291
Once the ttl manager is automatically closed after max ttl. And the PK may be rolled back after it, stop the ttl manager and fail the dml to avoid committing PK failure.
Without this PR, the worst case is p-dml cannot be aware of PK rollback, and keep flushing locks which block GC for a long time.
> p-dml: fail pipelined dml when max ttl exceeded (#1329)

- config/client.go
- internal/client/client_batch.go
- internal/client/client_test.go
Ref https://github.com/pingcap/tidb/issues/53222
https://github.com/tikv/client-go/pull/1098/files#diff-289d0ab3e9da9a88db8dcf8ed7095af6756da3ea8da38212b352742a83d93ba2L383
If do not cancel the request in time, the upper layer will wait until it times out, and we should cancel requests when no available connections and let the upper layer try another replica again.
Before This PR:
Benchmark test with stop 1 tikv store. Many slow query execution time exceed 1 min.
This PR:
Many slow query execution time is less than 25s.
> fix issue of doesn't fast fail request when no available connections

- internal/client/client_batch.go
- internal/client/client_test.go
```log
wait recvLoop timeout,timeout:30s, wait_duration:4.525µs:: context deadline exceeded
```
This error msg is too wired, timeout is `30s`, but real wait_duration is only has `4.525µs`?
> refine error msg

- internal/locate/region_request.go
- internal/locate/region_request3_test.go
Cherrypick https://github.com/tikv/client-go/pull/1115 to tidb-6.5-with-kv-timeout-feature branch.
> Fix the issue that leader change with new leader info cause invalidStore state and lead to unnecessary backoff (#1115)

- internal/locate/region_cache.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- tikv/region.go
- pick #1100
- [stale read] support increasing timeout when retry leader
- [stale read] support disabling retry follower when leader is unavailable
> make experimental improvements to replica selector

- internal/unionstore/pipelined_memdb.go
- internal/unionstore/union_store.go
- txnkv/transaction/txn.go
ref https://github.com/pingcap/tidb/issues/50215
This is to show performance characteristics of pipelined dml.
> feat: record flush_wait_ms in TxnInfo

- internal/locate/region_request.go
- internal/locate/region_request_test.go
> *: fix panic in get cause error

- txnkv/transaction/txn_file.go
Fix backoff with nil error. As `err` is always `nil`, `errors.WithMessagef(err,...` also returns `nil`, then `bo.Backoff` will panic.
> txn-file: Fix backoff with nil error

- txnkv/transaction/txn.go
This is a quick fix to avoid the transaction being left in aggressive locking state after panicking in `DoneAggressiveLocking`. While I haven't decide how to fix it in the most elegant approach, there should be a quick fix to avoid the problem, so that we have time to find the final solution more carefully.
Ref: https://github.com/pingcap/tidb/issues/53540#issuecomment-2132568080 , https://github.com/pingcap/tidb/issues/53540#issuecomment-2138089140
> Fix the problem that statement being oom-killed within DoneAggressiveLocking causing the transaction still in aggressive locking state

- internal/client/client.go
- internal/client/client_test.go
fix rpc client panic cause by concurrent close.
And add a test for it, before this PR, the run test with race flag will failed:
```go
▶ go test -race -run=TestConcurrentCloseConnPanic
panic: close of closed channel
goroutine 90 [running]:
github.com/tikv/client-go/v2/internal/client.(*batchConn).Close(...)
/Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client_batch.go:891
github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc00014a240)
/Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client.go:384 +0xdc
github.com/tikv/client-go/v2/internal/client.(*RPCClient).CloseAddrVer(0xc00011e230, {0x10503ec2e, 0xe}, 0xffffffffffffffff)
/Users/cs/code/goread/src/github.com/pingcap/client-go/internal/client/client.go:876 +0x500 …
```
> fix rpc client panic cause by concurrent close

- internal/unionstore/memdb.go
- internal/unionstore/pipelined_memdb.go
- internal/unionstore/union_store.go
- txnkv/transaction/txn.go
part of [pingcap/tidb#53832](https://github.com/pingcap/tidb/pull/53764)
Add a method to show whether the hook is set, to avoid redundantly setting it.
> Introduce a new method MemHookSet

- internal/locate/region_cache.go
- txnkv/transaction/txn.go
- txnkv/transaction/txn_file.go
- Acquire txn file availability from API of txn chunk writer.
- Refactor `chunkWriterClient` to reuse logics of retry for the two APIs.
> txn-file: Acquire txn file availability

- internal/resourcecontrol/resource_control.go
- txnkv/transaction/txn_file.go
- Calculate RU for txn file
Get RU result from `http://pd/metrics`, keyspace `7`:
1. Write 10MB pessimistic transaction
`resource_manager_resource_unit_write_request_unit_sum{name="7",type="tp"} 35633.62499999955`
2. Write 10MB txn file transaction
`resource_manager_resource_unit_write_request_unit_sum{name="7",type="tp"} 67347.73828124952`
3. Write 20MB pessimistic transaction
`resource_manager_resource_unit_write_request_unit_sum{name="7",type="tp"} 138614.98828124886`
4. Write 20MB txn file transaction
`resource_manager_resource_unit_write_request_unit_sum{name="7",type="tp"} 202043.21484374919`
> txn-file: Calculate RU

- internal/locate/region_request.go
Issue https://github.com/tikv/client-go/issues/1371
This message is printed when a request is tried on all replicas and is failed. Few failures (< 10) per tidb node are expected and it spams the logging for large cluster.
> removing spurious warning message in selector

- config/client.go
`enable-replica-selector-v2` has been removed by https://github.com/tikv/client-go/pull/1265
According to `Feature Removal Process`, I can't remove the config `enable-replica-selector-v2` directly in v8.2, it can only be deleted in v8.6. So I added this config back, but it was deprecated and does not take effect.
> add enable-replica-selector-v2 config back but mark it was deprecated

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/mockstore/mocktikv/pd.go
ref pingcap/tidb#54313 pingcap/tidb#54341
Some tools still need to keep compatibility with earlier version TiDB clusters, thus a fallback path of `BatchScanRegions` is required.
> region cache: fallback to ScanRegions when BatchScanRegions receive unimplement error

- txnkv/transaction/txn.go
This cherry-picks #1355 to tidb-7.5 branch.
> Fix the problem that statement being oom-killed within DoneAggressiveLocking causing the transaction still in aggressive locking state (#1355)

- txnkv/transaction/pipelined_flush.go
> feat: log flush_wait_duration

- txnkv/transaction/2pc.go
- txnkv/transaction/2pc_test.go
- txnkv/transaction/txn_file.go
- Check whether the txn chunk has no kv in the specified region and skip to write to it.
> txn-file: Skip write to empty region

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
> fix issue that store's liveness may incorrectly marked as unreachable when the store restarts with label changed

- internal/unionstore/pipelined_memdb.go
- internal/unionstore/union_store.go
- txnkv/transaction/pipelined_flush.go
Previous tracking of flush_wait is wrong. This PR fixes it.
It also logs the total execution time prior to commit, providing better performance insights.
> fix: duration logs for pipelined DML

- internal/locate/region_request.go
Log region request round failed log when total backoff duration is more than 1s.
> refine region request debug log

- txnkv/transaction/txn.go
This cherry-picks https://github.com/tikv/client-go/pull/1355 to tidb-8.1 branch.
> Fix the problem that statement being oom-killed within DoneAggressive Locking causing the transaction still in aggressive locking state (#1355)

- .github/workflows/test.yml
- .golangci.yml
- internal/unionstore/memdb.go
- util/misc.go
- util/misc_test.go
The current version `v1.51.2` of `golangci-lint` report false positive errors (see https://github.com/tikv/client-go/actions/runs/10214979208/job/28310744852?pr=1414):
```
❯ golangci-lint run
../../opt/go1.21.0/src/slices/sort.go:67:7: undefined: min (typecheck)
m = min(m, x[i])
^
../../opt/go1.21.0/src/slices/sort.go:97:7: undefined: max (typecheck)
m = max(m, x[i])
```
- Update version of `golangci-lint` to `v1.59.1` in CI.
- Fix new lint errors:
- Remove `depguard` linter as we do not deny any 3rd package. The `depguard` linter is by default in strict mode and deny and 3rd package. In another hand if change to `lax` mode the linter will complain that `depguard: must have an Allow and/or Deny package list`
- Use new `unsafe.SliceXXX` methods to replace deprecated `reflect.SliceHeader`. …
> *: Update golangci-lint to v1.59.1 and fix lint errors

- internal/unionstore/memdb.go
- internal/unionstore/memdb_arena.go
- internal/unionstore/pipelined_memdb.go
- internal/unionstore/union_store.go
- tikv/unionstore_export.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/txn.go
A common usage in TiDB is to access a same key multiple times consecutively. We can save subsequent traversals when this happen.
I tested oltp_write_only, no diff found compared with master.
In a YCSB 3M rows benchmark, the computation duration (total duration - flush wait) decreases, proving the optimization works as expected. We also observe a significant increase in flush_wait when applying this optimization. That should be a standalone problem to track and solve, IMO.
Master
insert 47.73-9.74=37.99s
update 30.74-2.78=27.96s
delete 23.81-5.98=17.83s
```
[pipelined_flush.go:304] ["[pipelined dml] start to commit transaction"] [conn=2669674502] [session_alias=] [keys=5999998] [flush_wait_duration=9.742798374s] [total_duration=47.735029816s] [size=3.506GB] [startTS=451525108111769604] …
```
> Let memdb cache last traversed node

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/locate/sorted_btree.go
Currently, client-go only supports batch reading of region information from pd, but not from region cache. 
If there is a large table with 200k regions, even if all regions are in memory, it still takes 0.8-0.9s to read all regions. 
This PR optimizes the querying times to the B-tree, the time consumption reduces by about 40%.
```
This PR
Running tool: /gosdk/go1.22.1/bin/go test -benchmem -run=^$ -bench ^BenchmarkBatchLocateKeyRanges$ github.com/tikv/client-go/v2/internal/locate --tags=intest --count=1 -v
goos: linux
goarch: amd64
pkg: github.com/tikv/client-go/v2/internal/locate
cpu: 13th Gen Intel(R) Core(TM) i9-13900KF
BenchmarkBatchLocateKeyRanges
BenchmarkBatchLocateKeyRanges-32    	    1116	   1305628 ns/op	 1412405 B/op	   10921 allocs/op
PASS
ok …
```
> region cache: batch find regions by key ranges from cache

- config/client.go
- txnkv/transaction/txn_file.go
Support RU discount for file based transaction.
RU base: `113895.00000000393`
Perform 10 x 32MB normal txn: `1.2529470000000296e+06`, cost: `139052`
Perform 10 x 32MB file-based txn: `1.3793565802734673e+06`, cost: `126409`
Perform 40 x 32MB normal txn: `5.942659016603314e+06`, cost: `4563302`
Perform 40 x 32MB file-based txn: `6.448379828322069e+06`, cost: `505720`
RU base: `7.138956353321901e+06`
Perform 80 x 32MB normal txn: `1.6308955402701495e+07`, cost: `9169999`
Perform 80 x 32MB file-based txn: `1.7320355780826386e+07`, cost: `1011400`
> txn-file: Support RU discount

- config/retry/backoff_test.go
- config/retry/config.go
- internal/locate/region_request.go
- tikvrpc/tikvrpc.go
ref pingcap/tidb#55388
We always retry stale read with snapshot read, so the backoff for it can be removed, because wait for safe ts catching up is meaningless for snapshot read.
> region_request: remove backoff for stale read

- internal/unionstore/memdb_arena.go
- internal/unionstore/memdb_test.go
> [tidb-cse-7.5] memdb: fix memdb snapshot get/iter is not actually snapshot 

- internal/unionstore/arena/arena.go
- internal/unionstore/memdb_art.go
- internal/unionstore/memdb_rbt.go
- internal/unionstore/memdb_test.go
- internal/unionstore/rbt/rbt.go
After #1389, we cache the last traversed node in memdb, but it's an atomic pointer, which need a heap allocation every time we update it, so the benchmark has little regression.
```
go test ./internal/unionstore -v -benchmem -bench=BenchmarkMemDbBufferSequential -run=^a -benchtime=1x
before  #1389
BenchmarkMemDbBufferSequential-8               1          42312917 ns/op        12576704 B/op         31 allocs/op
after #1389
BenchmarkMemDbBufferSequential-8               1          46407916 ns/op        15776704 B/op     200031 allocs/op
this pr
BenchmarkMemDbBufferSequential-8               1          44018167 ns/op        12576704 B/op         31 allocs/op
```
This PR also fixes some bugs of memdb:
- The refactor leave a mistake of the snapshot reverse iterator.
- The cached addr should be …
> memdb: use atomic u64 addr to reduce allocation

- txnkv/transaction/txn_file.go
- util/misc.go
- util/misc_test.go
- Get first key inside range of both region & txn chunk
- Otherwise, commit request will have duplicated keys as all txn chunks in the same region will get the same key.
- An alternative solution is just passing one key for every batch. But it's more reasonable that the commit keys is in the range of txn chunks.
From logs of tikv:
`[cmd="kv::command::txn_file start_ts: 452262720810778627 chunk_ids: 452262720810778634 user_meta: 01030014638CC246060500FC668CC24606 shard_ver: 70 inner_lower_bound: 748000000000000036 inner_upper_bound: 7480000000000000665F72 \"kv::command::commit [7800000174800000FF00000000645F7280FF0000000000000200FE] 452262720810778627 -> 452262720876314629 | region_id: 1298 region_epoch { conf_ver: 17 version: 70 } peer { id: 1385 store_id: 4 } max_execution_duration_ms: …
> txn-file: Get first key inside range of both region & txn chunk

- txnkv/transaction/txn_file.go
- Sort by chunks first during `groupToBatches`
- To properly handle the scene that batch with bigger chunk having region with smaller start key, which is caused by region merge during grouping.
> txn-file: Sort by chunks first during group to batches

- integration_tests/2pc_test.go
- integration_tests/async_commit_test.go
- txnkv/transaction/2pc.go
- txnkv/transaction/test_probe.go
- txnkv/transaction/txn.go
This PR adds two hooks to execute before the start of async-commit goroutine and after the finish of async-commit goroutines.
It can be used to add some external logic to track the lifecycle of the async-commit goroutines. For example, in `TiDB` we'll need to wait for the background goroutines to finish before shutdown.
> transaction: add hook for async commit to track the life cycle of the async-commit goroutine and secondary lock cleanup goroutine

- internal/unionstore/memdb_arena.go
- internal/unionstore/memdb_test.go
Cherry pick https://github.com/tikv/client-go/pull/1393 into tidb-7.1.
ref https://github.com/tikv/client-go/issues/1394
> memdb: fix memdb snapshot get/iter is not actually snapshot (#1393)

- config/client.go
- config/config_test.go
- internal/client/client.go
- internal/locate/store_cache.go
- tikv/kv.go
- change `grpc-keepalive-timeout` from uint to float64, for support millisecond timeout
> config: change grpc-keepalive-timeout from uint to float64, for support millisecond timeout

- internal/locate/region_request.go
- internal/locate/region_request_test.go
ref https://github.com/tikv/client-go/issues/1322
> [pick-8.1] region_request: ignore resource group errors that not relative storage layer (#1354)

- internal/unionstore/art/art.go
- internal/unionstore/art/art_arena.go
- internal/unionstore/art/art_node.go
- internal/unionstore/art/art_node_test.go
- internal/unionstore/art/art_test.go
- internal/unionstore/memdb_art.go
- internal/unionstore/memdb_bench_test.go
- internal/unionstore/memdb_norace_test.go
- internal/unionstore/memdb_test.go
This PR implements ART with basic get and set.
> membuffer: implement ART with basic get/set

- internal/locate/region_request.go
- internal/locate/region_request_test.go
ref https://github.com/tikv/client-go/issues/1322
> [pick-7.5]region_request: ignore resource group errors that not relative storage layer (#1354)

- internal/unionstore/arena/arena.go
- internal/unionstore/arena/arena_test.go
- internal/unionstore/art/art.go
- internal/unionstore/art/art_node.go
- internal/unionstore/memdb_norace_test.go
- internal/unionstore/memdb_test.go
- internal/unionstore/rbt/rbt.go
ref https://github.com/pingcap/tidb/issues/55287
This PR implements `Staging/Release/Cleanup` and `Checkpoint/RevertToCheckpoint` for ART, the behavior is exactly same with RBT.
>  membuffer: support staging & checkpoint for ART

- internal/unionstore/art/art.go
- internal/unionstore/art/art_iterator.go
- internal/unionstore/art/art_snapshot.go
- internal/unionstore/memdb.go
- internal/unionstore/memdb_art.go
- internal/unionstore/memdb_rbt.go
- internal/unionstore/memdb_test.go
This PR implements [Snapshot](https://github.com/tikv/client-go/blob/7d0f0bc93b5bae761fa1e7c9c4994686e6107cc3/internal/unionstore/union_store.go#L200-L205) and other methods of `MemBuffer` interface for ART.
> membuffer: implement snapshot get and iterator for ART

- examples/gcworker/go.mod
- examples/rawkv/go.mod
- examples/txnkv/1pc_txn/go.mod
- examples/txnkv/async_commit/go.mod
- examples/txnkv/delete_range/go.mod
- examples/txnkv/go.mod
- examples/txnkv/pessimistic_txn/go.mod
- examples/txnkv/unsafedestoryrange/go.mod
- internal/unionstore/art/art.go
- internal/unionstore/memdb_bench_test.go
- internal/unionstore/memdb_test.go
ART can also benefit from the cache of last visited leaf, this PR implement the cache, it's almost same as RBT's implementation.
The test result of new added `BenchmarkMemBufferCache`:
```text
// RBT, with cache, 1 cache-miss and 10 cache-hits for each key
BenchmarkMemBufferCache/RBT
BenchmarkMemBufferCache/RBT-32          10000000               185.9 ns/op             0 B/op          0 allocs/op
// master, no cache, 11 cache-miss for each key
BenchmarkMemBufferCache/ART
BenchmarkMemBufferCache/ART-32          10000000               223.3 ns/op             0 B/op          0 allocs/op
// this PR, with cache, 1 cache-miss and 10 cache-hits for each key
BenchmarkMemBufferCache/ART
BenchmarkMemBufferCache/ART-32          10000000               126.6 ns/op             0 …
```
> membuffer: implement cache for ART

- .github/workflows/compatibility.yml
- txnkv/transaction/2pc.go
This ensures that PK is the single source of truth for transaction status on the TiKV side. It prevents potential inconsistencies where the cached information might be more up-to-date than the info stored in the PK.
> Do not broadcast txn status when heartbeat fail

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
Ref: https://github.com/pingcap/tidb/issues/56757
When there is no leader information for all the returned regions, retry scan or batch scan region from PD but not return errors to the upper layer.
> region cache: retry scan or batch scan regions when returned region has no leader

- error/error.go
- internal/unionstore/art/art.go
- internal/unionstore/art/art_arena.go
- internal/unionstore/art/art_iterator.go
- internal/unionstore/art/art_iterator_test.go
- internal/unionstore/art/art_node.go
- internal/unionstore/art/art_node_test.go
- internal/unionstore/art/art_snapshot.go
- internal/unionstore/art/art_test.go
- internal/unionstore/memdb_test.go
- internal/unionstore/rbt/rbt.go
This PR tries to make the code simplify and increase the test coverage (only some unreachable paths are not covered).
> membuffer: improve ART's code and test coverage

- internal/locate/region_request.go
- internal/locate/region_request_test.go
ref https://github.com/tikv/client-go/issues/1322
> [pick-7.1] region_request: ignore resource group errors that not relative storag layer (#1354)

- internal/unionstore/art/art_iterator.go
- internal/unionstore/art/art_node.go
- internal/unionstore/art/art_node_test.go
- internal/unionstore/memdb_bench_test.go
In order to perform path compression in ART, we need to find the longest common prefix the keys in many places, when the common prefix is long, this can be slow.
This PR compares the keys by chunk. Because a chunk is a uint64 which can contains 8 bytes, this can improve the performance a lot when the common prefix is long.
- Long Common Prefix
```
BenchmarkMemBufferSetGetLongKey
BenchmarkMemBufferSetGetLongKey/ART
BenchmarkMemBufferSetGetLongKey/ART-32           1000000               874.3 ns/op          2149 B/op          0 allocs/op
BenchmarkMemBufferSetGetLongKey
BenchmarkMemBufferSetGetLongKey/ART
BenchmarkMemBufferSetGetLongKey/ART-32           1000000               524.5 ns/op          2149 B/op          0 allocs/op
```
- Common Cases
```
BenchmarkPut …
```
> membuffer: compare the keys of ART by chunk

- metrics/metrics.go
- oracle/oracle.go
- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
- tikv/kv.go
Ref: https://github.com/pingcap/tidb/issues/56809
> Support adaptive update interval for low resolution ts

- internal/unionstore/memdb_test.go
- internal/unionstore/rbt/rbt.go
- internal/unionstore/rbt/rbt_iterator.go
- internal/unionstore/rbt/rbt_test.go
close #1375, ref pingcap/tidb#56837
The issue #1375 figures out that the RBT membuffer cannot reuse free nodes which causes a memory leak. This pr uses marking the node as deleted to replace the actual deletion.
Pros:
- Because the memory arena cannot handle the memory fragmentation well, we avoid the memory leak by this mark-delete strategy.
Cons:
- In certain cases, the mark-delete tree may be taller than the actual deletion, which can slightly impact the performance.
> membuffer: fix memory leak in red-black tree

- examples/gcworker/go.mod
- examples/rawkv/go.mod
- examples/txnkv/1pc_txn/go.mod
- examples/txnkv/async_commit/go.mod
- examples/txnkv/delete_range/go.mod
- examples/txnkv/go.mod
- examples/txnkv/pessimistic_txn/go.mod
- examples/txnkv/unsafedestoryrange/go.mod
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/txn.go
1. Fix the potential data race caused by a mix use of `go` and `spawnWithStorePool`. Close https://github.com/pingcap/tidb/issues/57213
2. Make the broadcast in Rollback async to reduce the wait in Rollback operations.
> Fix the async broadcast & resolveFlushedLocks

- txnkv/transaction/2pc.go
- txnkv/transaction/pipelined_flush.go
Ref: tikv/tikv#17459
When the pipelined transaction is failed in commit phase, we should also broadcast the txn status and cleanup failed locks.
Manually inject error when committing primary key of pipelined transaction. 
```sql
MySQL [test]> set session tidb_dml_type=bulk;
Query OK, 0 rows affected (0.000 sec)
MySQL [test]> insert into _sbtest1 select * from sbtest1;
ERROR 1105 (HY000): [pipelined dml] mock error
```
- Before, the locks can block resolved  ts.
- This PR, the resolved ts is not blocked.
> clean up locks when p-dml is failed

- oracle/oracles/pd.go
Found and fixed these problems:
1. As updating last tick time is  moved into the `doUpdate` closure, and `nextUpdateInterval` calculates the value of recovering based on the last tick time, it causes the update interval unable to recover back.
2. TiDB calls `SetLowResolutionTimestampUpdateInterval` [every 30 seconds no matter whether the user changes it](https://github.com/pingcap/tidb/blob/153d5aaa3859a2a7c10150e2724e7edba1096b14/pkg/domain/domain.go#L1867). After adding the log about changing the update interval, then there becomes too many logs.
> Fix the problem that adaptive update interval doesn't recovers back and there's too much logs about setting the config

- internal/unionstore/art/art_arena.go
- internal/unionstore/art/art_snapshot.go
- internal/unionstore/art/art_snapshot_test.go
- internal/unionstore/memdb_test.go
ref pingcap/tidb#57425
The snapshot iterators always read from a snapshot of MemBuffer, but writes between `Next` calls can alter the structure of ART (see the "but explanation" section for details), potentially causing the snapshot iterator to read incorrect results.
This PR introduces a counter for active snapshots. When the counter is greater than 0, it indicates that old versions need to be retained for snapshot reads. In such cases, we store freed nodes in unused slices and delay the actual free operation to prevent them from being reused.
Add a counter for 
<details>
<summary>1. The snapshot iterator scans to node (click to expand the figure)</summary>
```text
│                                 │ 
│        iterator range           │ 
◄─────────────────────────────────► 
│ …
```
> memdb: retain old version nodes of ART to satisfy snapshot read

- .github/workflows/test.yml
- internal/unionstore/memdb.go
- internal/unionstore/memdb_arena.go
- internal/unionstore/memdb_iterator.go
- internal/unionstore/memdb_test.go
> membuffer: fix memory leak in red-black tree (#1483)

- integration_tests/1pc_test.go
- integration_tests/2pc_test.go
- integration_tests/assertion_test.go
- integration_tests/async_commit_test.go
- integration_tests/isolation_test.go
- integration_tests/lock_test.go
- txnkv/transaction/test_probe.go
- txnkv/transaction/txn.go
Ref: https://github.com/pingcap/tidb/issues/57165
Close: https://github.com/tikv/client-go/issues/1488
Export KVTxn.CommitTS to make it available in TiDB.
> Export commitTS of KVTxn

- metrics/metrics.go
- oracle/oracle.go
- oracle/oracles/export_test.go
- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
- tikv/kv.go
Cherry picks following PRs to tidb-7.5 branch:
* tso: merge lastTS and lastArrivalTS into an atomic pointer (#1054)
* Support adaptive update interval for low resolution ts (#1484) (#1491) 
* Fix the problem that adaptive update interval doesn't recovers back and there's too much logs about setting the config (#1502)
> Cherry pick bugfix #1054 & #1484 to tidb-7.5 branch

- metrics/metrics.go
- oracle/oracle.go
- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
- tikv/kv.go
Cherry picks #1484 to tidb-8.1 branch, along with #1502
> Support adaptive update interval for low resolution ts (#1484) 

- internal/unionstore/arena/arena.go
- internal/unionstore/art/art.go
- internal/unionstore/art/art_arena.go
- internal/unionstore/art/art_iterator.go
- internal/unionstore/art/art_node.go
- internal/unionstore/art/art_node_test.go
- internal/unionstore/art/art_snapshot.go
- internal/unionstore/art/art_test.go
Some refactor work to make the code of new ART implementation more understandable.
> memdb: refactor code of art to make it more understandable

- integration_tests/2pc_test.go
- txnkv/transaction/test_probe.go
- txnkv/transaction/txn.go
Ref: https://github.com/pingcap/tidb/issues/58279
> Fix the problem that ttlManager may stop working if no need to lock after retry aggressive locking

- internal/locate/region_cache.go
- internal/locate/sorted_btree.go
- metrics/metrics.go
ref https://github.com/tikv/pd/issues/7431
Enhance monitoring of active followers. When we encounter region's issues, there are clues to follow.
> metrics: add StaleRegionFromPDCounter

- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
The `setLastTS` can be called concurrently, so that the `tso` and `arrival` may have different order, `lastTSO1.tso < lastTSO2.tso` meanwhile `lastTSO1.arrival > lastTSO2.arrival`. In this case, when `lastTS` is set to `lastTSO1`, the update of `lastTSO2` will fail and later when we check `lastTS`, it's not true last.
This PR changes the `setLastTS` that it'll always push the `lastTS` to the max TSO we received.
> oracle: `setLastTS` always push tso to higher value

- .github/workflows/compatibility.yml
The TiDB compatibility tests in client-go can be disabled in the merge ci. These tests make modifying client-go very cumbersome after the repository split. In practice, updating the client-go dependency in TiDB already serves as a compatibility test.
> CI: disable tidb compatible test in merge CI

- internal/locate/region_request.go
Wrap the logic of handling failpoint `tikvStoreSendReqResult` into a function to make the main logic of `SendReqCtx` function more concise and friendly to maintain.
> region_request: tiny refactor - init function failpointSendReqResult

- internal/locate/region_request.go
Ref https://github.com/tikv/tikv/issues/17916
The error will directly propagate to user and abort current stmt.
The string match is more suitable for cherry-picking to older versions, we may consider introducing a new error type in master branch.
> Handle error invalid_max_ts_update

- metrics/metrics.go
- oracle/oracle.go
- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
- tikv/kv.go
Cherry pick #1484 and #1502 to tidb-6.5
> pick-6.5: Support adaptive update interval for low resolution ts (#1484)

- internal/locate/region_cache.go
close #1544
`store.addr` is mutable, it gets updated when: 1. `initResolve` 2. `refreshFullStoreList` , to avoid data race, we use storeID (which is immutable) as the value of the metric label.
> region_cache: fix a potential data race on store.addr

- internal/locate/region_request.go
- txnkv/txnsnapshot/snapshot.go
Fix the following two minor bugs found by code review:
1. [here](https://github.com/tikv/client-go/blob/2eba2f614b38e2905cc46ea8f0fc6d40ed6a0ccf/internal/locate/region_request.go#L864) the func may `return nil, nil, retryTimes, nil`
2. [here](https://github.com/tikv/client-go/blob/2eba2f614b38e2905cc46ea8f0fc6d40ed6a0ccf/txnkv/txnsnapshot/snapshot.go#L439) the func may return without unlock
> *: fix two minor bugs

- config/client.go
- internal/locate/region_cache.go
- internal/mockstore/mocktikv/pd.go
- tikv/region.go
Issue Number: ref https://github.com/tikv/pd/issues/8678
Add a global circuit breaker to the context of each call to get region data from PD.  
The default circuit breaker is in the disabled state and has no effect. 
This PR also exposes a method to tweak circuit breaker settings which can be used from TiDB layer to enable and configure it.
> integrate circuitbreaker for region calls

- txnkv/txnsnapshot/snapshot.go
| Workload | Threads | QPS (this PR) | QPS (baseline) | Diff |
| -------- | ------: | ------------: | -------------: | ---: |
| batchget |      64 |      22437.15 |       21908.98 | 2.4% |
| Workload | Threads |  QPS  | P99 Lat (this PR) | P99 Lat (baseline) | Diff  |
| -------- | ------: | ----: | ----------------: | -----------------: | ----: |
| batchget |      64 | 16000 |            6.67ms |             6.91ms | -3.5% |
> txnkv: optimize batch-get by reducing overhead of backoffer

- internal/client/client_interceptor.go
Do not wrap resouce control logic into an interceptor to reduce overhead.
```
0.11s 0.035% 0.035%     31.90s 10.15%  github.com/tikv/client-go/v2/internal/client.interceptedClient.SendRequest
0.32s   0.1%  0.14%     24.79s  7.88%  github.com/pingcap/tidb/pkg/store/driver.(*injectTraceClient).SendRequest
0.08s 0.025% 0.025%     33.97s 10.59%  github.com/tikv/client-go/v2/internal/client.interceptedClient.SendRequest
0.30s 0.094%  0.18%     24.61s  7.67%  github.com/pingcap/tidb/pkg/store/driver.(*injectTraceClient).SendRequest
```
| Workload | Threads | QPS (this PR) | QPS (baseline) | Diff |
| -------- | ------: | ------------: | -------------: | ---: |
| pointget |      64 |      87831.47 |       86159.20 | 1.9% |
| batchget |      64 |      22290.08 |       22037.33 | 1.1% |
> client: refactor intercepted client

- internal/apicodec/codec.go
- internal/apicodec/codec_v1.go
- internal/apicodec/codec_v2.go
- internal/client/client.go
- internal/client/client_collapse.go
- internal/client/client_test.go
- internal/locate/region_request.go
- internal/locate/region_request_test.go
- internal/mockstore/mocktikv/rpc.go
- tikv/test_util.go
- tikvrpc/cmds_generated.go
- tikvrpc/gen.sh
- tikvrpc/tikvrpc.go
1. let RPCClient attach request context to avoid attaching multiple times at upper layers.
2. let Codec use a request pool to avoid mem allocs.
| Workload | Threads | QPS (this PR) | QPS (baseline) | Diff |
| -------- | ------: | ------------: | -------------: | ---: |
| pointget |      64 |      88480.65 |       87868.89 | 0.7% |
| batchget |      64 |      22442.88 |       22165.04 | 1.3% |
> *: reduce overhead of codec client

- internal/client/client.go
- internal/client/metrics_collector.go
- internal/client/metrics_collector_test.go
- metrics/metrics.go
| Workload | Threads | QPS (this PR) | QPS (baseline) | Diff |
| -------- | ------: | ------------: | -------------: | ---: |
| pointget |      64 |      88416.74 |       87059.32 | 1.6% |
| batchget |      64 |      22450.64 |       21999.43 | 2.1% |
This PR
Baseline
> metrics: optimize rpc latency related metrics

- txnkv/txnsnapshot/snapshot.go
When build TiDB with PGO, batch-get may still has `copystack` operation, this pr will avoid copy stack in batch-get.
Related PR:
- https://github.com/tikv/client-go/pull/1535
- https://github.com/pingcap/tidb/pull/58630
Benchmark
> avoid copy stack in batch-get

- internal/locate/region_request3_test.go
- internal/locate/region_request_state_test.go
- internal/locate/replica_selector.go
- internal/locate/replica_selector_test.go
issue number : https://github.com/tikv/tikv/issues/17422
It is the extension of the original PR https://github.com/tikv/client-go/pull/1509. I have observed that in case of hot regions, leaders are inaccessible and stale reads are retried as follower_follower. I have added a change if leader is not reachable or epoch doesn't mach than retry stale read as stale instead of follower.
> retry stale read as stale if leader is not accessible

- txnkv/txnsnapshot/snapshot.go
> (tidb-8.5) Do not set txn scope in snapshot

- txnkv/txnsnapshot/snapshot.go
> (tidb-6.5) Do not set txn scope in snapshot

- txnkv/txnsnapshot/snapshot.go
> (tidb-8.1) Do not set txn scope in snapshot

- txnkv/txnsnapshot/snapshot.go
> (tidb-7.5) Do not set txn scope in snapshot

- txnkv/txnsnapshot/snapshot.go
> (tidb-7.1) Do not set txn scope in snapshot

- tikv/kv.go
**Problem Statement**
etcd client would only run `Sync` after `AutoSyncInterval` (30 seconds), which makes tikv client vulnerable to the failure of endpoints provided in `addrs` before the first sync happens. Specific failure scenario:
1. tidb is initialized with a `--path=endpoint`
2. tidb successfully established connection to the `endpoint`
3. n < 30 seconds after, endpoint fails (e.g. k8s control plane is upgrading the pod)
4. etcd client is no longer connected
5. Safe checkpoint expires and `CheckVisibility` in `KVStore` start to error out
**Fix**
We explicitly synchronize client endpoints with endpoints from etcd membership during client initialization phase. etcd client would continue to do periodic sync, we just force first sync to happen in the init phase.
> sync etcd endpoints immediately after initializing the client

- internal/locate/region_request.go
> (tidb-6.5) Use global txn scope when validating ts

- internal/locate/region_request.go
> (tidb-7.1) Use global txn scope when validating ts

- internal/locate/region_request.go
> (tidb-7.5) Use global txn scope when validating ts

- internal/locate/region_request.go
> (tidb-8.5) Use global txn scope when validating ts

- internal/locate/region_request.go
> (tidb-8.1) Use global txn scope when validating ts

- internal/locate/region_request.go
- txnkv/transaction/pipelined_flush.go
close #1577
The default range task size is too large for p-dml, which makes the concurrent resolve works bad, e.g., all the regions are pending in one worker and other workers are just waiting. Meanwhile, the utilization of TiKV CPU is low, and the resolve progress can take a long time.
https://github.com/tikv/client-go/blob/279dcd5b29a2df8797237bb09e41924d52a73fe0/txnkv/rangetask/range_task.go#L54
This PR set the task size to 1 for p-dml, so that the resolve progress can run at the concurrency given by user.
The resolve lock speed:
- nightly: 44m21s
- this PR: 14m19s
The progress logs work well with this change:
```log
[2025/02/18 03:27:35.952 +00:00] [INFO] [range_task.go:167] ["range task started"] [name=pipelined-dml-commit-456090845481533442] …
```
> p-dml: resolve locks concurrently

- internal/locate/region_request.go
This PR extracts the iteration of retry loop in `SendReqCtx` into `sendReqState.next`. We will reuse `sendReqState` in async client API.
> locate: refactor RegionRequestSender.SendReqCtx

- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
ref https://github.com/pingcap/tidb/issues/59402
Do not return errors in the ts validator. Only logs.
> (tidb-6.5) Ignore errors in ts validator

- internal/locate/region_cache.go
ref https://github.com/tikv/pd/issues/8678
The default settings are wrong, the unit should be the second.
> locate: fix the default settings of circuit breaker

- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
ref pingcap/tidb#59402
Only validate read ts for stale read and those who set `tidb_snapshot`
> (tidb-7.5) Validate ts only for stale read

- util/async/core.go
- util/async/core_test.go
- util/async/runloop.go
- util/async/runloop_test.go
> util: define and implement core interfaces for async api

- internal/locate/region_request.go
- txnkv/transaction/pipelined_flush.go
Cherry pick #1584 to `tidb-8.5` branch.
---
close #1577
The default range task size is too large for p-dml, which makes the concurrent resolve works bad, e.g., all the regions are pending in one worker and other workers are just waiting. Meanwhile, the utilization of TiKV CPU is low, and the resolve progress can take a long time.
https://github.com/tikv/client-go/blob/279dcd5b29a2df8797237bb09e41924d52a73fe0/txnkv/rangetask/range_task.go#L54
This PR set the task size to 1 for p-dml, so that the resolve progress can run at the concurrency given by user.
The resolve lock speed:
- nightly: 44m21s
- this PR: 14m19s
The progress logs work well with this change:
```log
[2025/02/18 03:27:35.952 +00:00] [INFO] [range_task.go:167] ["range task started"] …
```
> p-dml: resolve locks concurrently (#1584)

- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
This PR adds a retry to `ValidateReadTS` to avoid a false-positive when the checked ts comes from a different source other than the current pdOracle. This can happen in some non-TiDB caller (e.g. BR, lightning).
The `ValidateReadTS` function may use `getCurrentTSForValidation` to get a ts, which internally uses a singleflight. So it's possible that a later call to `ValidateReadTS` reuses an older on-the-way single flight and returns an older ts. If the ts to be checked comes from outside the current `pdOralce` (so that it's not cached by the low resolution ts), it may cause false positive.
The solution is to add a  retry: when `ValidateReadTS` check failed with a ts returned by `getCurrentTSForValidation`, try it one more time. So when the second call to `getCurrentTSForValidation` must …
> Add a retry when getting ts from PD for validating read ts

- internal/locate/region_request.go
ref https://github.com/tikv/client-go/pull/1565#issuecomment-2689512700
> locate: fix TestTiKVClientReadTimeout

- oracle/oracles/local.go
- oracle/oracles/mock.go
- oracle/oracles/pd.go
- oracle/oracles/pd_test.go
ref https://github.com/pingcap/tidb/issues/59402
Only validate read ts for stale read and those who set `tidb_snapshot`
> (tidb-7.1) Validate ts only for stale read

- kv/kv.go
- metrics/metrics.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/txn.go
This PR mainly forcus to replace some existing perssimistic stats with lockCtx.Stats struct, and move the TiKVPessimisticLockKeysDuration metric to tidb side, since the final merged lockCtx.Stats will be ready in tidb side.
Using lockCtx.Stats to replace existing LockKeys_Duration stats have several advantages:
1. Won't miss any lock time when the lock is not successfully accquired at last.
2. Don't rely on the Waited flag to record lock time
3. No need to keep similar stats in lockCtx and lockCtx.Stats
> Refine pessimistic lock related metrics and stats

- metrics/metrics.go
Ref: https://github.com/pingcap/tidb/issues/59990
> metrics: adjust bucket count to reduce metrics data

- config/retry/backoff.go
- config/retry/backoff_test.go
- rawkv/rawkv.go
- tikv/split_region.go
- txnkv/txnlock/lock_resolver.go
- txnkv/txnsnapshot/snapshot.go
ref https://github.com/pingcap/tidb/issues/60271
For current Backoffer code, when we send rpc concurrently for multiple regions, the Backoffer object will be forked multiple times to keep isolated. However, the forked Backoffer's info is never merged into its parent, causing Backoffer info lose. In this PR, we use the slowest execution path to merge back Backoffer info.
Two Backoffer fork in 2pc.go keeps unchanged, because I have no confidence to ensure funcitonality correctness:
https://github.com/tikv/client-go/blob/2b8c6a77616c9b43ccdc5c115e122276423db477/txnkv/transaction/2pc.go#L2258
https://github.com/tikv/client-go/blob/2b8c6a77616c9b43ccdc5c115e122276423db477/txnkv/transaction/2pc.go#L2303
> Fix backoff lose info when forked

- internal/apicodec/codec_v2.go
It should be `EncodeKey` rather than `EncodeRegionKey`
Fix issue https://github.com/pingcap/tidb/issues/60716
Manually tested:
```
mysql> create table t (id int);
Query OK, 0 rows affected (0.10 sec)
mysql> insert into t values (1);
Query OK, 1 row affected (0.02 sec)
curl http://127.0.0.1:10080/mvcc/key/test/t/1
{
"key": "74800000000000007F5F728000000000000001",
"region_id": 1021,
"value": {
"info": {
"writes": [
{
"start_ts": 457681415883718657,
"commit_ts": 457681415883718659,
"short_value": "gAABAAAAAQEAAQ=="
}
]
}
}
}
```
Unit test is not easy to construct now, it's better to add UT after https://github.com/tikv/client-go/issues/1637
> apicodec: fix a typo when encoding request for CmdMvccGetByKey

- config/retry/backoff.go
- config/retry/backoff_test.go
- examples/gcworker/go.mod
- examples/rawkv/go.mod
- examples/txnkv/1pc_txn/go.mod
- examples/txnkv/async_commit/go.mod
- examples/txnkv/delete_range/go.mod
- examples/txnkv/go.mod
- examples/txnkv/pessimistic_txn/go.mod
- examples/txnkv/unsafedestoryrange/go.mod
- go.mod
- go.sum
- integration_tests/1pc_test.go
- integration_tests/2pc_test.go
- integration_tests/async_commit_fail_test.go
- integration_tests/go.mod
- integration_tests/go.sum
- integration_tests/store_test.go
- internal/locate/region_request.go
- internal/locate/region_request3_test.go
- internal/locate/region_request_test.go
- internal/locate/replica_selector_test.go
- txnkv/transaction/2pc.go
- txnkv/transaction/commit.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/prewrite.go
- txnkv/txnsnapshot/scan.go
- txnkv/txnsnapshot/snapshot.go
> txn: handle undetermined error in client go

- .github/workflows/integration.yml
- integration_tests/health_feedback_test.go
- integration_tests/lock_test.go
- integration_tests/pd_api_test.go
- integration_tests/pd_next_gen.toml
- integration_tests/pipelined_memdb_test.go
- integration_tests/scan_test.go
- integration_tests/snapshot_fail_test.go
- integration_tests/snapshot_test.go
- integration_tests/tikv_next_gen.toml
- integration_tests/util_test.go
Blocked by the fix of the bug where start_ts = conflicting commi_ts.
> ci: add next-gen integration tests

- integration_tests/2pc_test.go
- internal/locate/region_request.go
- tikvrpc/tikvrpc.go
- txnkv/transaction/2pc.go
- txnkv/transaction/cleanup.go
- txnkv/transaction/commit.go
- txnkv/transaction/pessimistic.go
- txnkv/transaction/pipelined_flush.go
- txnkv/transaction/prewrite.go
Ignore the kill flag when trying to send CommitRequest, PessimisticRollbackRequest and BatchRollbackRequest so that the locks can be cleaned up properly.
Fix https://github.com/pingcap/tidb/issues/61454 .
> txnkv: prevent some actions from being interrupted by kill

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
- internal/mockstore/mocktikv/cluster.go
ref pingcap/tidb#53850, pingcap/tidb#62040
Cherry pick #1052 to 7.5 and support buckets for `ScanRegions` of mocktikv.
> (tidb-7.5) Support buckets for `ScanRegions` of mocktikv

- examples/gcworker/go.mod
- examples/rawkv/go.mod
- examples/txnkv/1pc_txn/go.mod
- examples/txnkv/async_commit/go.mod
- examples/txnkv/delete_range/go.mod
- examples/txnkv/go.mod
- examples/txnkv/pessimistic_txn/go.mod
- examples/txnkv/unsafedestoryrange/go.mod
- integration_tests/snapshot_test.go
- internal/locate/replica_selector.go
- internal/locate/replica_selector_test.go
- tikvrpc/tikvrpc.go
- txnkv/txnsnapshot/snapshot.go
Cherry pick #1663 to tidb-8.5
---
ref pingcap/tidb#61745
The [`replicaReadAdjuster`](https://github.com/tikv/client-go/blob/96b6487fac411fea3b4e15170d419d7b8307d6f2/txnkv/txnsnapshot/snapshot.go#L147-L148) can choose leader and follower replica after a request is created.
When the request is created as a replica-read request but fallback to leader read by `replicaReadAdjuster`, we need to set the [`replica_read`](https://github.com/pingcap/kvproto/blob/dc99a8f6e3487e3a73013c2e7d7cf9d5cbb55c45/proto/kvrpcpb.proto#L861) to false as well. Unless it can perform a meaningless read-index in leader and harm the performance.
Many read-index proposals.
Few read-index proposals.
> snapshot: set `ReplicaRead` to false when `ReplicaReadType` fallbacks to `ReplicaReadLeader` (#1663)

- internal/locate/region_cache.go
- internal/locate/region_cache_test.go
Cherry pick #1698 to tidb-7.5
---
For some functions that bypass the region cache, we should leave the exist region valid.
| Initial State | Bypass Region Cache | Finish State (old region) | Finish State (new region) |
| - | - | - | - |
| valid | yes | valid | valid |
| valid | no | valid | valid |
| invalid | yes | valid | invalid |
| invalid | no | valid | invalid |
> region cache: do not invalidate the valid region cache when new region cache is loaded (#1698)

- util/async/runloop_test.go
close #1682
When run test with `-race`, `runtime.Gosched` may not works as the test expected.
> util/async: make TestExecConcurrent stable

- internal/client/client_async_test.go
The test assumed that the handle callback should be called within 1ms, which is not always true.
> client: make TestSendRequestAsyncTimeout/CanceledOnHandle stable

- internal/locate/region_cache.go
Tracked by issue https://github.com/tikv/client-go/issues/1647
Reset the **needReloadOnAccess** flag for a region when the region cache fails to reload region information(from pd) for an obsolete record.
Please refer to the issue description for the motivation behind this change.
> region cache: Preserve needReloadOnAccess Flag on Region Cache Reload Failure

- integration_tests/async_commit_test.go
- integration_tests/lock_test.go
- txnkv/txnlock/lock_resolver.go
- txnkv/txnlock/lock_resolver_test.go
- txnkv/txnlock/test_probe.go
Ref: https://github.com/pingcap/tidb/issues/59494
1. Do not call `checkSecondaries` if the transaction status is determined for async commit transactions. 
2. Small refactor on the `TxnStatus` usages.
3. Do not use `ttl = 0` setting in test cases.
> txn: fix resolver cache usage for async commit

- internal/apicodec/codec_v2.go
- util/intest/in_unittest.go
- util/intest/not_in_unittest.go
When next-gen is enabled in TiDB, many unit tests failed because `codecV2` cannot decode the empty key. These unit tests rely on the unistore, which doesn't have a assumption about the key existence of `ErrConflict`:
https://github.com/pingcap/tidb/blob/60e5a4b8b7087eef42e9478cbe2efa4c154876fe/pkg/store/mockstore/unistore/tikv/server.go#L267
This PR makes `codecV2` supports decoding the empty key. It is also compatible with `codecV1`:
```
func (c *codecV1) DecodeKey(key []byte) ([]byte, error) {
return key, nil
}
```
> apicodec: do not decode empty key for codec v2

- txnkv/txnsnapshot/snapshot.go
> txnkv: backport some optimizations for batch get
